/*
 * Copyright (C) 2025-2026 QuantumForge Development Team.
 */
package quantumforge.hpc;

import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import quantumforge.ssh.ShellQuotes;
import quantumforge.ver.Version;

/**
 * PBS/Torque adapter with typed #PBS directives.
 */
public final class PbsSchedulerAdapter implements SchedulerAdapter {

    private static final Pattern JOB_ID = Pattern.compile(
            "([0-9]+)(?:\\.[A-Za-z0-9._-]+)?");

    @Override
    public String name() {
        return "pbs";
    }

    @Override
    public String generateScript(String jobName, SchedulerResources resources, List<String[]> commands) {
        SchedulerResources res = resources == null
                ? SchedulerResources.builder().build() : resources;
        String name = jobName == null || jobName.isBlank() ? "quantumforge" : jobName.trim();
        int ncpus = Math.max(1, res.getNtasks() * res.getCpusPerTask());
        StringBuilder out = new StringBuilder();
        out.append("#!/usr/bin/env bash\n");
        out.append("set -euo pipefail\n");
        out.append("# Generated by ").append(Version.VERSION_NAME).append(' ')
                .append(Version.VERSION).append('\n');
        out.append("#PBS -N ").append(sanitizeToken(name)).append('\n');
        if (!res.getPartition().isEmpty()) {
            out.append("#PBS -q ").append(sanitizeToken(res.getPartition())).append('\n');
        }
        out.append("#PBS -l select=").append(res.getNodes())
                .append(":ncpus=").append(ncpus)
                .append(":mpiprocs=").append(res.getNtasks())
                .append(":ompthreads=").append(res.getCpusPerTask()).append('\n');
        out.append("#PBS -l walltime=").append(sanitizeToken(res.getWalltime())).append('\n');
        if (!res.getAccount().isEmpty()) {
            out.append("#PBS -W group_list=").append(sanitizeToken(res.getAccount())).append('\n');
        }
        if (!res.getMemory().isEmpty()) {
            out.append("#PBS -l mem=").append(sanitizeToken(res.getMemory())).append('\n');
        }
        out.append("#PBS -j oe\n\n");
        out.append("if [ -n \"${PBS_O_WORKDIR:-}\" ]; then\n");
        out.append("  cd \"${PBS_O_WORKDIR}\"\n");
        out.append("fi\n");
        out.append("export OMP_NUM_THREADS=").append(res.getCpusPerTask()).append("\n\n");
        if (commands != null) {
            int i = 0;
            for (String[] command : commands) {
                if (command == null || command.length == 0) {
                    continue;
                }
                out.append("echo \"==> stage ").append(i++).append("\"\n");
                out.append("set --");
                for (String token : command) {
                    out.append(' ').append(ShellQuotes.single(token));
                }
                out.append("\n\"$@\"\n\n");
            }
        }
        return out.toString();
    }

    @Override
    public Optional<String> parseJobId(String submitOutput) {
        if (submitOutput == null || submitOutput.isBlank()) {
            return Optional.empty();
        }
        // Typical: "12345.cluster.domain" or "12345.host"
        Matcher matcher = JOB_ID.matcher(submitOutput.trim());
        if (matcher.find()) {
            return Optional.of(matcher.group(1));
        }
        return Optional.empty();
    }

    @Override
    public String[] cancelCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        return new String[] {"qdel", schedulerJobId.trim()};
    }

    @Override
    public String[] statusCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        return new String[] {"qstat", "-f", schedulerJobId.trim()};
    }

    /**
     * PBS/Torque documents the absence shape: qstat against an unknown job id
     * prints "qstat: Unknown Job Id ..." on stderr and exits non-zero.
     */
    @Override
    public boolean isJobAbsent(String stderrText) {
        return stderrText != null && stderrText.contains("Unknown Job Id");
    }

    @Override
    public String[] submitCommand(String remoteScriptPath) {
        if (remoteScriptPath == null || remoteScriptPath.isBlank() || remoteScriptPath.contains("..")) {
            throw new IllegalArgumentException("invalid remote script path");
        }
        return new String[] {"qsub", remoteScriptPath};
    }

    static String sanitizeToken(String value) {
        return value.trim().replaceAll("[^A-Za-z0-9._:@+/-]", "_");
    }

    private static void requireJobId(String schedulerJobId) {
        if (schedulerJobId == null || !schedulerJobId.trim().matches("[0-9]+(?:\\.[A-Za-z0-9._-]+)?")) {
            throw new IllegalArgumentException("invalid PBS job id: " + schedulerJobId);
        }
    }
}
