/*
 * Copyright (C) 2025-2026 QuantumForge Development Team.
 */
package quantumforge.hpc;

import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import quantumforge.ssh.ShellQuotes;
import quantumforge.ver.Version;

/**
 * Fujitsu PJM / Technical Computing Suite adapter with typed #PJM directives.
 *
 * <p>The command grammar is pinned from Fujitsu's own PJM documentation and is
 * deliberately minimal - only what can be stated with confidence:</p>
 * <ul>
 *   <li>submit = {@code pjsub}; cancel = {@code pjdel}; per-job query =
 *       {@code pjstat -S} (site docs additionally show {@code pjstat -H -S}
 *       for completed-job history). Exit-code/absence interpretation stays
 *       the caller's honest duty - this adapter never declares a job
 *       cancelled;</li>
 *   <li>directives emitted: job name ({@code #PJM -N}), resource group from
 *       the partition field ({@code #PJM -L "rscgrp=..."}), node count
 *       ({@code #PJM -L "node=N"}), wall clock ({@code #PJM -L
 *       "elapse=HH:MM:SS"}) and joined output ({@code #PJM -j});</li>
 *   <li>NOT emitted: an {@code --mpi} process-placement line (its shape is
 *       site-dependent) and account/memory tokens (no equivalent exists in
 *       this grammar). The header comment in the generated script states both
 *       omissions instead of inventing tokens;</li>
 *   <li>job ids are decimal; the SLURM array syntax {@code id_index} is
 *       refused here (array grammar is SLURM-only, mirroring the cancel-plan
 *       contract).</li>
 * </ul>
 */
public final class PjmSchedulerAdapter implements SchedulerAdapter {

    private static final Pattern JOB_ID = Pattern.compile(
            "(?i)(?:pjsub\\s+)?job\\s+(\\d+)");

    @Override
    public String name() {
        return "pjm";
    }

    @Override
    public String generateScript(String jobName, SchedulerResources resources, List<String[]> commands) {
        SchedulerResources res = resources == null
                ? SchedulerResources.builder().build() : resources;
        String name = jobName == null || jobName.isBlank() ? "quantumforge" : jobName.trim();
        StringBuilder out = new StringBuilder();
        out.append("#!/usr/bin/env bash\n");
        out.append("set -euo pipefail\n");
        out.append("# Generated by ").append(Version.VERSION_NAME).append(' ')
                .append(Version.VERSION).append('\n');
        out.append("# PJM notes: no --mpi placement line and no account/memory tokens are emitted -\n");
        out.append("# the first is site-shaped, the second has no PJM equivalent; both are left\n");
        out.append("# to the site mpiexec defaults rather than invented here.\n");
        out.append("#PJM -N ").append(sanitizeToken(name)).append('\n');
        if (!res.getPartition().isEmpty()) {
            out.append("#PJM -L \"rscgrp=").append(sanitizeToken(res.getPartition()))
                    .append("\"\n");
        }
        out.append("#PJM -L \"node=").append(res.getNodes()).append("\"\n");
        out.append("#PJM -L \"elapse=").append(sanitizeToken(toPjmTime(res.getWalltime())))
                .append("\"\n");
        out.append("#PJM -j\n");
        out.append("\nexport OMP_NUM_THREADS=").append(res.getCpusPerTask()).append("\n\n");
        if (commands != null) {
            int i = 0;
            for (String[] command : commands) {
                if (command == null || command.length == 0) {
                    continue;
                }
                out.append("echo \"==> stage ").append(i++).append("\"\n");
                out.append("set --");
                for (String token : command) {
                    out.append(' ').append(ShellQuotes.single(token));
                }
                out.append("\n\"$@\"\n\n");
            }
        }
        return out.toString();
    }

    @Override
    public Optional<String> parseJobId(String submitOutput) {
        if (submitOutput == null || submitOutput.isBlank()) {
            return Optional.empty();
        }
        // Typical: "[INFO] PJM 0000 pjsub Job 12345678 submitted."
        Matcher matcher = JOB_ID.matcher(submitOutput);
        if (matcher.find()) {
            return Optional.of(matcher.group(1));
        }
        String trimmed = submitOutput.trim();
        if (trimmed.matches("\\d+")) {
            return Optional.of(trimmed);
        }
        return Optional.empty();
    }

    @Override
    public String[] cancelCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        return new String[] {"pjdel", schedulerJobId.trim()};
    }

    @Override
    public String[] statusCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        // Per-job detail query; site docs add -H for completed-job history.
        return new String[] {"pjstat", "-S", schedulerJobId.trim()};
    }

    /**
     * PJM stays FAIL-CLOSED: no confidently documented pjstat absence needle
     * exists in the sources pinned for this adapter, so this override is
     * deliberately absent - the interface default (never absent) stands and an
     * unexplained pjstat failure is reported as unreadable, never as "gone".
     */
    @Override
    public String[] submitCommand(String remoteScriptPath) {
        if (remoteScriptPath == null || remoteScriptPath.isBlank()
                || remoteScriptPath.contains("..")) {
            throw new IllegalArgumentException("invalid remote script path");
        }
        return new String[] {"pjsub", remoteScriptPath};
    }

    static String toPjmTime(String walltime) {
        // Accept HH:MM:SS or HH:MM; PJM elapse wants HH:MM:SS.
        if (walltime == null || walltime.isBlank()) {
            return "01:00:00";
        }
        String t = walltime.trim();
        if (t.matches("\\d+:\\d+")) {
            return t + ":00";
        }
        return t;
    }

    static String sanitizeToken(String value) {
        return value.trim().replaceAll("[^A-Za-z0-9._:@+/-]", "_");
    }

    private static void requireJobId(String schedulerJobId) {
        if (schedulerJobId == null || !schedulerJobId.trim().matches("\\d+")) {
            throw new IllegalArgumentException(
                    "invalid PJM job id (decimal digits only - the SLURM 'id_index'"
                            + " array syntax is not PJM grammar): " + schedulerJobId);
        }
    }

    @Override
    public ArraySubmitSpec arraySubmitSpec() {
        // Fujitsu TCS manual (the same manual family whose pjsub/pjdel/pjstat
        // grammar batch 126 verified): bulk-job submission is
        // `pjsub --bulk --sparam <start>-<end> job.sh`; each bulk element sees
        // PJM_BULKNUM. Distinctively NOT a SLURM --array clone.
        return ArraySubmitSpec.supported("PJM_BULKNUM",
                (from, to) -> new String[] {"--bulk", "--sparam", from + "-" + to},
                "Fujitsu TCS manual: bulk-job submission (pjsub --bulk --sparam)");
    }
}
