/*
 * Copyright (C) 2025-2026 QuantumForge Development Team.
 */
package quantumforge.hpc;

import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import quantumforge.ssh.ShellQuotes;
import quantumforge.ver.Version;

/**
 * Grid Engine / SGE / UGE adapter with typed #$ directives.
 */
public final class SgeSchedulerAdapter implements SchedulerAdapter {

    private static final Pattern JOB_ID = Pattern.compile(
            "(?i)(?:Your job|job)\\s+(\\d+)");

    @Override
    public String name() {
        return "sge";
    }

    @Override
    public String generateScript(String jobName, SchedulerResources resources, List<String[]> commands) {
        SchedulerResources res = resources == null
                ? SchedulerResources.builder().build() : resources;
        String name = jobName == null || jobName.isBlank() ? "quantumforge" : jobName.trim();
        int slots = Math.max(1, res.getNtasks() * res.getCpusPerTask());
        StringBuilder out = new StringBuilder();
        out.append("#!/usr/bin/env bash\n");
        out.append("set -euo pipefail\n");
        out.append("# Generated by ").append(Version.VERSION_NAME).append(' ')
                .append(Version.VERSION).append('\n');
        out.append("#$ -N ").append(sanitizeToken(name)).append('\n');
        out.append("#$ -cwd\n");
        out.append("#$ -j y\n");
        out.append("#$ -pe smp ").append(slots).append('\n');
        out.append("#$ -l h_rt=").append(sanitizeToken(toSgeTime(res.getWalltime()))).append('\n');
        if (!res.getPartition().isEmpty()) {
            out.append("#$ -q ").append(sanitizeToken(res.getPartition())).append('\n');
        }
        if (!res.getAccount().isEmpty()) {
            out.append("#$ -A ").append(sanitizeToken(res.getAccount())).append('\n');
        }
        if (!res.getMemory().isEmpty()) {
            out.append("#$ -l h_vmem=").append(sanitizeToken(res.getMemory())).append('\n');
        }
        out.append("\nexport OMP_NUM_THREADS=").append(res.getCpusPerTask()).append("\n\n");
        if (commands != null) {
            int i = 0;
            for (String[] command : commands) {
                if (command == null || command.length == 0) {
                    continue;
                }
                out.append("echo \"==> stage ").append(i++).append("\"\n");
                out.append("set --");
                for (String token : command) {
                    out.append(' ').append(ShellQuotes.single(token));
                }
                out.append("\n\"$@\"\n\n");
            }
        }
        return out.toString();
    }

    @Override
    public Optional<String> parseJobId(String submitOutput) {
        if (submitOutput == null || submitOutput.isBlank()) {
            return Optional.empty();
        }
        Matcher matcher = JOB_ID.matcher(submitOutput);
        if (matcher.find()) {
            return Optional.of(matcher.group(1));
        }
        String trimmed = submitOutput.trim();
        if (trimmed.matches("\\d+")) {
            return Optional.of(trimmed);
        }
        return Optional.empty();
    }

    @Override
    public String[] cancelCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        return new String[] {"qdel", schedulerJobId.trim()};
    }

    @Override
    public String[] statusCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        return new String[] {"qstat", "-j", schedulerJobId.trim()};
    }

    /**
     * Grid Engine documents the absence shape: qstat -j against an unknown job
     * prints "Following jobs do not exist:" on stderr and exits non-zero.
     */
    @Override
    public boolean isJobAbsent(String stderrText) {
        return stderrText != null && stderrText.contains("do not exist");
    }

    @Override
    public String[] submitCommand(String remoteScriptPath) {
        if (remoteScriptPath == null || remoteScriptPath.isBlank() || remoteScriptPath.contains("..")) {
            throw new IllegalArgumentException("invalid remote script path");
        }
        return new String[] {"qsub", remoteScriptPath};
    }

    static String toSgeTime(String walltime) {
        // Accept HH:MM:SS or HH:MM; SGE often wants HH:MM:SS.
        if (walltime == null || walltime.isBlank()) {
            return "01:00:00";
        }
        String t = walltime.trim();
        if (t.matches("\\d+:\\d+")) {
            return t + ":00";
        }
        return t;
    }

    static String sanitizeToken(String value) {
        return value.trim().replaceAll("[^A-Za-z0-9._:@+/-]", "_");
    }

    private static void requireJobId(String schedulerJobId) {
        if (schedulerJobId == null || !schedulerJobId.trim().matches("\\d+")) {
            throw new IllegalArgumentException("invalid SGE job id: " + schedulerJobId);
        }
    }
}
