/*
 * Copyright (C) 2025-2026 QuantumForge Development Team.
 */
package quantumforge.hpc;

import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import quantumforge.ssh.ShellQuotes;
import quantumforge.ver.Version;

/**
 * SLURM adapter with typed #SBATCH directives (no free-form core concatenation).
 */
public final class SlurmSchedulerAdapter implements SchedulerAdapter {

    private static final Pattern JOB_ID = Pattern.compile(
            "(?i)(?:Submitted batch job|job)\\s+(\\d+)");

    @Override
    public String name() {
        return "slurm";
    }

    @Override
    public String generateScript(String jobName, SchedulerResources resources, List<String[]> commands) {
        SchedulerResources res = resources == null
                ? SchedulerResources.builder().build() : resources;
        String name = jobName == null || jobName.isBlank() ? "quantumforge" : jobName.trim();
        StringBuilder out = new StringBuilder();
        out.append("#!/usr/bin/env bash\n");
        out.append("set -euo pipefail\n");
        out.append("# Generated by ").append(Version.VERSION_NAME).append(' ')
                .append(Version.VERSION).append('\n');
        out.append("#SBATCH --job-name=").append(sanitizeToken(name)).append('\n');
        out.append("#SBATCH --nodes=").append(res.getNodes()).append('\n');
        out.append("#SBATCH --ntasks=").append(res.getNtasks()).append('\n');
        out.append("#SBATCH --cpus-per-task=").append(res.getCpusPerTask()).append('\n');
        out.append("#SBATCH --time=").append(sanitizeToken(res.getWalltime())).append('\n');
        if (!res.getPartition().isEmpty()) {
            out.append("#SBATCH --partition=").append(sanitizeToken(res.getPartition())).append('\n');
        }
        if (!res.getAccount().isEmpty()) {
            out.append("#SBATCH --account=").append(sanitizeToken(res.getAccount())).append('\n');
        }
        if (!res.getQos().isEmpty()) {
            out.append("#SBATCH --qos=").append(sanitizeToken(res.getQos())).append('\n');
        }
        if (!res.getMemory().isEmpty()) {
            out.append("#SBATCH --mem=").append(sanitizeToken(res.getMemory())).append('\n');
        }
        out.append("#SBATCH --output=%x-%j.out\n");
        out.append("#SBATCH --error=%x-%j.err\n\n");
        out.append("cd \"${SLURM_SUBMIT_DIR}\"\n");
        out.append("export OMP_NUM_THREADS=").append(res.getCpusPerTask()).append("\n\n");
        if (commands != null) {
            int i = 0;
            for (String[] command : commands) {
                if (command == null || command.length == 0) {
                    continue;
                }
                out.append("echo \"==> stage ").append(i++).append("\"\n");
                out.append("set --");
                for (String token : command) {
                    out.append(' ').append(ShellQuotes.single(token));
                }
                out.append("\n\"$@\"\n\n");
            }
        }
        return out.toString();
    }

    @Override
    public Optional<String> parseJobId(String submitOutput) {
        if (submitOutput == null || submitOutput.isBlank()) {
            return Optional.empty();
        }
        Matcher matcher = JOB_ID.matcher(submitOutput);
        if (matcher.find()) {
            return Optional.of(matcher.group(1));
        }
        // Bare numeric line fallback
        String trimmed = submitOutput.trim();
        if (trimmed.matches("\\d+")) {
            return Optional.of(trimmed);
        }
        return Optional.empty();
    }

    @Override
    public String[] cancelCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        return new String[] {"scancel", schedulerJobId.trim()};
    }

    @Override
    public String[] statusCommand(String schedulerJobId) {
        requireJobId(schedulerJobId);
        return new String[] {"squeue", "-j", schedulerJobId.trim(), "-h", "-o", "%T"};
    }

    @Override
    public String[] submitCommand(String remoteScriptPath) {
        if (remoteScriptPath == null || remoteScriptPath.isBlank() || remoteScriptPath.contains("..")) {
            throw new IllegalArgumentException("invalid remote script path");
        }
        return new String[] {"sbatch", remoteScriptPath};
    }

    static String sanitizeToken(String value) {
        // Keep #SBATCH values free of whitespace/metacharacters.
        return value.trim().replaceAll("[^A-Za-z0-9._:@+/-]", "_");
    }

    private static void requireJobId(String schedulerJobId) {
        if (schedulerJobId == null || !schedulerJobId.trim().matches("\\d+")) {
            throw new IllegalArgumentException("invalid SLURM job id: " + schedulerJobId);
        }
    }
}
