/*
 * Copyright (C) 2025-2026 QuantumForge Team
 */

package quantumforge.input;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;

import quantumforge.atoms.model.Atom;
import quantumforge.atoms.model.Cell;
import quantumforge.com.math.Matrix3D;

/**
 * Generates mathematically consistent and logically structured input files for the
 * ABINIT electronic structure engine, mapping crystal lattices (rprim/acell),
 * fractional coordinates (xred), and atomic types/species (typat/znucl) (Roadmap #114).
 */
public final class QEAbinitInputBuilder {

    private final Cell cell;
    private final double ecutHa;       // Kinetic energy cutoff in Hartree
    private final String xcFunctional; // e.g. LDA, PBE

    public QEAbinitInputBuilder(Cell cell, double ecutHa, String xc) {
        this.cell = Objects.requireNonNull(cell, "cell");
        this.ecutHa = Math.max(5.0, ecutHa);
        this.xcFunctional = xc == null ? "PBE" : xc.trim().toUpperCase(Locale.ROOT);
    }

    public Cell getCell() { return this.cell; }
    public double getEcutHa() { return this.ecutHa; }
    public String getXcFunctional() { return this.xcFunctional; }

    /**
     * Emits the complete, cleanly formatted ABINIT input file text.
     */
    public String generateInput() {
        StringBuilder sb = new StringBuilder();
        sb.append("# ABINIT input generated by QuantumForge\n\n");

        // 1. Basic calculation parameters
        sb.append("tolvrs   1.0d-8      # SCF convergence threshold\n");
        sb.append(String.format(Locale.ROOT, "ecut     %.1f         # Cutoff energy (Hartree)\n", ecutHa));
        sb.append("nstep    50          # Max SCF steps\n\n");

        // 2. Crystal lattice definition (rprim & acell)
        double[][] lattice = cell.copyLattice(); // in Angstroms
        sb.append("# Lattice vectors (Angstroms)\n");
        sb.append("acell    1.0 1.0 1.0 Angstrom\n");
        sb.append("rprim\n");
        sb.append(String.format(Locale.ROOT, "  %12.8f  %12.8f  %12.8f\n", lattice[0][0], lattice[0][1], lattice[0][2]));
        sb.append(String.format(Locale.ROOT, "  %12.8f  %12.8f  %12.8f\n", lattice[1][0], lattice[1][1], lattice[1][2]));
        sb.append(String.format(Locale.ROOT, "  %12.8f  %12.8f  %12.8f\n", lattice[2][0], lattice[2][1], lattice[2][2]));
        sb.append("\n");

        // 3. Species and types (znucl, typat)
        Atom[] atoms = cell.listAtoms(true);
        if (atoms == null || atoms.length == 0) {
            return sb.toString();
        }

        // Map unique elements to standard atomic numbers (znucl) and type indices (typat)
        Map<String, Integer> uniqueElements = new LinkedHashMap<>();
        int typeCounter = 1;
        for (Atom atom : atoms) {
            if (atom == null || atom.isSlaveAtom()) continue;
            String name = atom.getName();
            if (!uniqueElements.containsKey(name)) {
                uniqueElements.put(name, typeCounter++);
            }
        }

        sb.append("# Atomic types and numbers\n");
        sb.append("ntypat   ").append(uniqueElements.size()).append("\n");
        sb.append("znucl    ");
        for (String el : uniqueElements.keySet()) {
            sb.append(getAtomicNumber(el)).append(" ");
        }
        sb.append("\n\n");

        // 4. Coordinates (xred - fractional coordinates)
        sb.append("natom    ").append(atoms.length).append("\n");
        sb.append("typat    ");
        for (Atom atom : atoms) {
            if (atom == null || atom.isSlaveAtom()) continue;
            sb.append(uniqueElements.get(atom.getName())).append(" ");
        }
        sb.append("\n\n");

        // Compute fractional coordinates: s = cart * lattice_inv
        double[][] inv = Matrix3D.inverse(lattice);
        if (inv == null) {
            return sb.toString();
        }

        sb.append("xred\n");
        for (Atom atom : atoms) {
            if (atom == null || atom.isSlaveAtom()) continue;
            double[] diff = {atom.getX(), atom.getY(), atom.getZ()};
            double s0 = diff[0] * inv[0][0] + diff[1] * inv[1][0] + diff[2] * inv[2][0];
            double s1 = diff[0] * inv[0][1] + diff[1] * inv[1][1] + diff[2] * inv[2][1];
            double s2 = diff[0] * inv[0][2] + diff[1] * inv[1][2] + diff[2] * inv[2][2];

            // Wrap in-plane boundaries to [0, 1)
            s0 = s0 - Math.floor(s0);
            s1 = s1 - Math.floor(s1);
            s2 = s2 - Math.floor(s2);

            sb.append(String.format(Locale.ROOT, "  %12.8f  %12.8f  %12.8f  # %s\n", s0, s1, s2, atom.getName()));
        }

        return sb.toString();
    }

    private static int getAtomicNumber(String element) {
        switch (element.trim().toUpperCase(Locale.ROOT)) {
            case "H": return 1;
            case "HE": return 2;
            case "LI": return 3;
            case "BE": return 4;
            case "B": return 5;
            case "C": return 6;
            case "N": return 7;
            case "O": return 8;
            case "F": return 9;
            case "NE": return 10;
            case "NA": return 11;
            case "MG": return 12;
            case "AL": return 13;
            case "SI": return 14;
            case "P": return 15;
            case "S": return 16;
            case "CL": return 17;
            case "AR": return 18;
            case "K": return 19;
            case "CA": return 20;
            case "FE": return 26;
            case "NI": return 28;
            case "PT": return 78;
            default: return 1; // Fallback
        }
    }
}
