/* Copyright (C) 2025-2026 QuantumForge Development Team. */
package quantumforge.input.schema;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

/**
 * Machine-mined grammar of the 24 AUXILIARY QE programs (batch 159),
 * generated by {@code scripts/qe_aux_schema_miner.py} per release tag
 * qe-7.2 .. qe-7.6 (tag sha256 fingerprints in {@link QEAuxSchemaData}):
 * bgw2pw, pw2bgw, pwcond, pprism, oscdft_et, oscdft, dynmat, matdyn,
 * postahc, q2r, d3hess, neb, cp, cppp, lanczos, spectrum, davidson,
 * magnon, eels, xspectra, spectra_correction, spectra_manipulation,
 * ld1, all_currents.
 *
 * <p>Honesty rules carried by this schema:</p>
 * <ul>
 *   <li>21 programs mine QE's OWN machine grammar INPUT_*.def files (the
 *       files the published INPUT_*.html pages are generated FROM):
 *       membership, declared types, declared defaults, REQUIRED flags and
 *       documented option literals ('opt -val' records) with per-literal
 *       presence masks - the literals are a DOC layer (SOFT hints), never a
 *       refusal law by themselves;</li>
 *   <li>xspectra / spectra_correction / spectra_manipulation have NO .def
 *       grammar: their namelist declarations are mined from compilable
 *       source (INPUT_XSPECTRA/PLOT/PSEUDOS/CUT_OCC from
 *       read_input_and_bcast.f90; INPUT_MANIP from spectra_correction.f90,
 *       shared by the two tools as their own docs state); types there are
 *       UNKNOWN honestly (they live in module files outside the mined
 *       span) - no type is invented;</li>
 *   <li>an unknown namelist keyword aborts EVERY one of these programs at
 *       the Fortran READ (language-level fact), mirrored as ERROR by the
 *       audit; a HARD accepted set exists ONLY where mined verbatim
 *       (spectra_correction's option STOP-set), nowhere else - tolerated
 *       remappings are not claimed;</li>
 *   <li>presence masks ride the 5-bit scheme of
 *       {@link QENamelistSchema#VERSIONS}; programs whose grammar drifts
 *       between tags (many do: oscdft, d3hess, postahc, pwcond, neb, cp and
 *       others change at 7.4/7.5/7.6) carry that fact in the masks, not in
 *       prose.</li>
 * </ul>
 */
public final class QEAuxSchema {

    /** QE documentation root (pages of record per program). */
    public static final String DOCS_ROOT = "https://www.quantum-espresso.org/Doc/";

    /** One mined keyword row: one name inside one namelist of one program. */
    public static final class Row {
        private final String program;
        private final String namelist;
        private final String name;
        private final String type;
        private final String defaultText;
        private final boolean required;
        private final int versionMask;
        private final List<OptionLiteral> options;

        Row(String program, String namelist, String name, String type,
            String defaultText, boolean required, int versionMask,
            List<OptionLiteral> options) {
            this.program = program;
            this.namelist = namelist;
            this.name = name;
            this.type = type;
            this.defaultText = defaultText;
            this.required = required;
            this.versionMask = versionMask;
            this.options = List.copyOf(options);
        }

        /** Program label (lowercase, e.g. "pwcond"). */
        public String getProgram() { return this.program; }

        /** Owning namelist (uppercase, e.g. INPUTCOND). */
        public String getNamelist() { return this.namelist; }

        /** Keyword name as declared (case preserved by the source). */
        public String getName() { return this.name; }

        /** Declared type (def -type or source decl; UNKNOWN honestly). */
        public String getType() { return this.type; }

        /** Verbatim declared default text, null when none is declared. */
        public String getDefaultText() { return this.defaultText; }

        /** True when the def status {} marks the keyword REQUIRED. */
        public boolean isRequired() { return this.required; }

        /** Presence mask across {@link QENamelistSchema#VERSIONS}. */
        public int getVersionMask() { return this.versionMask; }

        /** Documented option literals with per-literal masks (SOFT layer). */
        public List<OptionLiteral> getOptions() { return this.options; }

        /** True when this keyword exists for the given QE version string. */
        public boolean presentIn(String version) {
            int index = QENamelistSchema.indexOfVersion(version);
            return index >= 0 && (this.versionMask & (1 << index)) != 0;
        }

        /** First window label carrying this keyword ("" when never). */
        public String firstPresentLabel() {
            return firstLabel(this.versionMask);
        }
    }

    /** One documented option literal with its presence mask (SOFT hints). */
    public static final class OptionLiteral {
        private final String value;
        private final int versionMask;

        OptionLiteral(String value, int versionMask) {
            this.value = value;
            this.versionMask = versionMask;
        }

        /** Literal as documented (verbatim). */
        public String getValue() { return this.value; }

        /** Presence mask across {@link QENamelistSchema#VERSIONS}. */
        public int getVersionMask() { return this.versionMask; }
    }

    /** One verbatim HARD fact with its presence mask (bounded, mined). */
    public static final class MaskedFact {
        private final String text;
        private final int versionMask;

        MaskedFact(String text, int versionMask) {
            this.text = text;
            this.versionMask = versionMask;
        }

        /** Verbatim fact text (e.g. the spectra option STOP-set). */
        public String getText() { return this.text; }

        /** Presence mask across {@link QENamelistSchema#VERSIONS}. */
        public int getVersionMask() { return this.versionMask; }
    }

    private static final List<Row> ROWS;
    private static final Map<String, List<Row>> BY_PROGRAM;
    private static final Map<String, Map<String, List<Row>>> BY_PROGRAM_KEY;
    private static final Map<String, String> DOC_PAGE;
    private static final List<MaskedFact> FACTS;

    static {
        List<Row> rows = QEAuxSchemaData.buildRows();
        ROWS = List.copyOf(rows);
        Map<String, List<Row>> byProgram = new LinkedHashMap<>();
        Map<String, Map<String, List<Row>>> byKey = new LinkedHashMap<>();
        for (Row row : rows) {
            byProgram.computeIfAbsent(row.getProgram(), k -> new ArrayList<>())
                    .add(row);
            byKey.computeIfAbsent(row.getProgram(), k -> new LinkedHashMap<>())
                    .computeIfAbsent(row.getName().toLowerCase(Locale.ROOT),
                            k -> new ArrayList<>())
                    .add(row);
        }
        Map<String, List<Row>> frozenProgram = new LinkedHashMap<>();
        byProgram.forEach((k, v) -> frozenProgram.put(k, List.copyOf(v)));
        BY_PROGRAM = Collections.unmodifiableMap(frozenProgram);
        Map<String, Map<String, List<Row>>> frozenKey = new LinkedHashMap<>();
        byKey.forEach((k, v) -> {
            Map<String, List<Row>> inner = new LinkedHashMap<>();
            v.forEach((k2, v2) -> inner.put(k2, List.copyOf(v2)));
            frozenKey.put(k, Collections.unmodifiableMap(inner));
        });
        BY_PROGRAM_KEY = Collections.unmodifiableMap(frozenKey);
        Map<String, String> docs = new LinkedHashMap<>();
        for (String item : QEAuxSchemaData.buildDocPages()) {
            int tilde = item.indexOf('~');
            if (tilde > 0) {
                docs.put(item.substring(0, tilde), item.substring(tilde + 1));
            }
        }
        DOC_PAGE = Collections.unmodifiableMap(docs);
        List<MaskedFact> facts = new ArrayList<>();
        for (String item : QEAuxSchemaData.buildFacts()) {
            int tilde = item.lastIndexOf('~');
            if (tilde < 0) {
                facts.add(new MaskedFact(item, QENamelistSchema.ALL_VERSIONS_MASK));
                continue;
            }
            int mask;
            try {
                mask = Integer.decode(item.substring(tilde + 1));
            } catch (NumberFormatException bad) {
                mask = QENamelistSchema.ALL_VERSIONS_MASK;
            }
            facts.add(new MaskedFact(item.substring(0, tilde), mask));
        }
        FACTS = List.copyOf(facts);
    }

    private QEAuxSchema() { }

    /** Factory used by the generated table only. */
    public static Row row(String program, String namelist, String name,
                          String type, String defaultText, boolean required,
                          int versionMask, String optionCsv) {
        List<OptionLiteral> options = new ArrayList<>();
        if (optionCsv != null && !optionCsv.isEmpty()) {
            for (String item : optionCsv.split(",", -1)) {
                int tilde = item.lastIndexOf('~');
                if (tilde < 0) {
                    options.add(new OptionLiteral(item,
                            QENamelistSchema.ALL_VERSIONS_MASK));
                    continue;
                }
                int mask;
                try {
                    mask = Integer.decode(item.substring(tilde + 1));
                } catch (NumberFormatException bad) {
                    mask = QENamelistSchema.ALL_VERSIONS_MASK;
                }
                options.add(new OptionLiteral(item.substring(0, tilde), mask));
            }
        }
        return new Row(program, namelist, name, type, defaultText, required,
                versionMask, options);
    }

    /** Every mined program label, in the miner order. */
    public static List<String> programs() {
        return List.copyOf(BY_PROGRAM.keySet());
    }

    /** Mined keyword count (union across the window; test-pinned). */
    public static int rowCount() { return ROWS.size(); }

    /** All keyword rows of one program in declaration order (empty if unknown). */
    public static List<Row> entries(String program) {
        return BY_PROGRAM.getOrDefault(normalize(program), List.of());
    }

    /** Case-insensitive keyword lookup within one program (all its namelists). */
    public static List<Row> lookup(String program, String keyword) {
        if (keyword == null) {
            return List.of();
        }
        String key = keyword.trim();
        int paren = key.indexOf('(');
        if (paren > 0 && key.endsWith(")")) {
            key = key.substring(0, paren).trim();
        }
        return BY_PROGRAM_KEY.getOrDefault(normalize(program), Map.of())
                .getOrDefault(key.toLowerCase(Locale.ROOT), List.of());
    }

    /** Namelists of one program in first-appearance order (mined). */
    public static List<String> namelists(String program) {
        List<String> out = new ArrayList<>();
        for (Row row : entries(program)) {
            if (!out.contains(row.getNamelist())) {
                out.add(row.getNamelist());
            }
        }
        return List.copyOf(out);
    }

    /** Programs owning a given namelist name (detection aid, may be many). */
    public static List<String> programsForNamelist(String namelist) {
        List<String> out = new ArrayList<>();
        if (namelist == null) {
            return out;
        }
        String wanted = namelist.trim().toUpperCase(Locale.ROOT);
        for (String program : BY_PROGRAM.keySet()) {
            if (namelists(program).contains(wanted)) {
                out.add(program);
            }
        }
        return List.copyOf(out);
    }

    /** QE doc page URL of record for a program ("" when unmined). */
    public static String docPage(String program) {
        String page = DOC_PAGE.get(normalize(program));
        return page == null ? "" : DOCS_ROOT + page;
    }

    /** Bounded verbatim HARD facts with masks. */
    public static List<MaskedFact> facts() { return FACTS; }

    /** Facts relevant to one program (prefix "program: "). */
    public static List<MaskedFact> factsFor(String program) {
        List<MaskedFact> out = new ArrayList<>();
        String prefix = normalize(program) + ": ";
        for (MaskedFact fact : FACTS) {
            if (fact.getText().startsWith(prefix)) {
                out.add(fact);
            }
        }
        return List.copyOf(out);
    }

    /** First window label carrying a mask bit ("" when none). */
    public static String firstLabel(int mask) {
        for (int i = 0; i < QENamelistSchema.VERSIONS.size(); i++) {
            if ((mask & (1 << i)) != 0) {
                return QENamelistSchema.VERSIONS.get(i);
            }
        }
        return "";
    }

    /** Last window label carrying a mask bit ("" when none). */
    public static String lastLabel(int mask) {
        for (int i = QENamelistSchema.VERSIONS.size() - 1; i >= 0; i--) {
            if ((mask & (1 << i)) != 0) {
                return QENamelistSchema.VERSIONS.get(i);
            }
        }
        return "";
    }

    private static String normalize(String program) {
        return program == null ? "" : program.trim().toLowerCase(Locale.ROOT);
    }
}
