/* GENERATED by scripts/qe_card_schema_miner.py - do not hand-edit.
 * Mined from QE Modules/read_cards.f90 at tags qe-7.2 .. qe-7.6,
 * 7.2: sha256=9493979efd6e4a60e8c43f74ea5547881614172aaae2c1eff91c91795ea3d269,
 * 7.3: sha256=bd5a5c186362b5e83fb782ae335d2dac501a4f1426381ef36457cfd003b007bd,
 * 7.4: sha256=c34c0b15a39f53f18aa62c912faa0df92f34e4b4f37410ca1b7b65c4fa63d5f2,
 * 7.5: sha256=f28673f2a04bb3bddf8c5e3a50d5b8654ef7a553df3fc1328af9b6f36f3cc566,
 * 7.6: sha256=9ac5be9ff31d8479cd3da2850294bbca11d1e89453be7e0dc55f6eeae88bde33,
 * fetched 2026-07-21 from github.com/QEF/q-e (blob-filtered clone).
 * Provenance rules: dispatch chain verbatim (incl. prog gates); ELSE
 * fallback = 'Warning: card ... ignored' (unknown card tolerated, never a
 * read error); option literals from the matches/imatches IF-chains;
 * ELSE-arm dispositions FATAL / TOLERATED_DEFAULT / TOLERATED_SILENT_DEFAULT
 * come from the arm's own statements; content rules beyond the mined
 * facts stay with QEInputValidator. */
package quantumforge.input.schema;

import java.util.ArrayList;
import java.util.List;

/** Generated mined QE card-grammar table (qe-7.2..7.6 read_cards.f90). */
final class QECardSchemaData {

    static List<QECardSchema.Dispatch> buildDispatch() {
        List<QECardSchema.Dispatch> out = new ArrayList<>();
        out.add(QECardSchema.dispatch("ATOMIC_SPECIES", "trim(card) == 'ATOMIC_SPECIES'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("ATOMIC_POSITIONS", "trim(card) == 'ATOMIC_POSITIONS'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("ATOMIC_FORCES", "trim(card) == 'ATOMIC_FORCES'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("CONSTRAINTS", "trim(card) == 'CONSTRAINTS'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("DIPOLE", "trim(card) == 'DIPOLE'", true, "", 0x1F));
        out.add(QECardSchema.dispatch("ESR", "trim(card) == 'ESR'", true, "", 0x1F));
        out.add(QECardSchema.dispatch("K_POINTS", "trim(card) == 'K_POINTS'", false, "CP", 0x1F));
        out.add(QECardSchema.dispatch("ADDITIONAL_K_POINTS", "trim(card) == 'ADDITIONAL_K_POINTS'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("OCCUPATIONS", "trim(card) == 'OCCUPATIONS'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("CELL_PARAMETERS", "trim(card) == 'CELL_PARAMETERS'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("REF_CELL_PARAMETERS", "trim(card) == 'REF_CELL_PARAMETERS'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("ATOMIC_VELOCITIES", "trim(card) == 'ATOMIC_VELOCITIES'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("KSOUT", "trim(card) == 'KSOUT'", false, "PW", 0x1F));
        out.add(QECardSchema.dispatch("PLOT_WANNIER", "trim(card) == 'PLOT_WANNIER'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("WANNIER_AC", "trim(card) == 'WANNIER_AC' .and. ( prog == 'WA' )", false, "", 0x1F));
        out.add(QECardSchema.dispatch("SOLVENTS", "trim(card) == 'SOLVENTS' .AND. trism", false, "", 0x1F));
        out.add(QECardSchema.dispatch("TOTAL_CHARGE", "trim(card) == 'TOTAL_CHARGE'", false, "", 0x1F));
        out.add(QECardSchema.dispatch("HUBBARD", "trim(card) == 'HUBBARD'", false, "", 0x1F));
        return out;
    }

    static List<QECardSchema.CardGrammar> buildGrammars() {
        List<QECardSchema.CardGrammar> out = new ArrayList<>();
        out.add(QECardSchema.grammar("ATOMIC_POSITIONS", "FATAL", 0x1F, "TOLERATED_DEFAULT", 0x1F, "unknown option for ATOMIC_POSITION; bare card name: DEPRECATED infomsg + defaulted to 'bohr'/'alat' (prog-dependent)", "O:CRYSTAL_SG~0x1F,O:CRYSTAL~0x1F,O:BOHR~0x1F,O:ANGSTROM~0x1F,O:ALAT~0x1F", ""));
        out.add(QECardSchema.grammar("K_POINTS", "TOLERATED_SILENT_DEFAULT", 0x1F, "TOLERATED_SILENT_DEFAULT", 0x1F, "defaulted to 'tpiba' silently", "O:AUTOMATIC~0x1F,O:CRYSTAL~0x1F,O:TPIBA~0x1F,O:GAMMA~0x1F", "_B~0x1F,_C~0x1F"));
        out.add(QECardSchema.grammar("CELL_PARAMETERS", "TOLERATED_DEFAULT", 0x1F, "TOLERATED_DEFAULT", 0x1F, "DEPRECATED infomsg + defaulted to 'none'", "O:BOHR~0x1F,O:ANGSTROM~0x1F,O:ALAT~0x1F", ""));
        out.add(QECardSchema.grammar("REF_CELL_PARAMETERS", "TOLERATED_SILENT_DEFAULT", 0x1F, "TOLERATED_SILENT_DEFAULT", 0x1F, "defaulted to 'alat' silently", "O:BOHR~0x1F,O:ANGSTROM~0x1F", ""));
        out.add(QECardSchema.grammar("ATOMIC_FORCES", "IGNORED", 0x1F, "IGNORED", 0x1F, "", "", ""));
        out.add(QECardSchema.grammar("ATOMIC_VELOCITIES", "IGNORED", 0x1F, "IGNORED", 0x1F, "", "", ""));
        out.add(QECardSchema.grammar("OCCUPATIONS", "IGNORED", 0x1F, "IGNORED", 0x1F, "", "", ""));
        out.add(QECardSchema.grammar("HUBBARD", "FATAL", 0x1F, "FATAL", 0x1F, "unknown option for HUBBARD; bare card name: errore in ELSE arm", "O:ORTHO-ATOMIC~0x1F,O:NORM-ATOMIC~0x1F,T:-ATOMIC~0x1F,T:ORTHOATOMIC~0x1F,T:NORMATOMIC~0x1F,O:ATOMIC~0x1F,O:WF~0x1F,O:PSEUDO~0x1F", ""));
        out.add(QECardSchema.grammar("SOLVENTS", "FATAL", 0x1F, "TOLERATED_DEFAULT", 0x1F, "unknown option for SOLVENTS; bare card name: DEPRECATED infomsg + defaulted to '1/cell'", "O:1/CELL~0x1F,O:MOL/L~0x1F,O:G/CM^3~0x1F", ""));
        return out;
    }

    /** Verbatim mined facts (bounded): duplicate-card erorres, K_POINTS automatic mesh rules, HUBBARD projector traps. */
    static List<String> buildFacts() {
        return List.of(
            "CALL errore( ' card_atomic_species ', ' two occurrences'",
            "CALL errore( ' card_atomic_species ', ' two occurrences of the same atomic label '",
            "CALL errore( ' card_atomic_forces ', ' two occurrences '",
            "CALL errore( ' card_kpoints ', ' two occurrences'",
            "CALL errore( ' card_occupations ', ' two occurrences'",
            "CALL errore( ' card_cell_parameters ', ' two occurrences'",
            "CALL errore( ' card_reference_cell_parameters ', ' two occurrences'",
            "CALL errore( ' card_ion_velocities ', ' two occurrences'",
            "CALL errore( ' card_ksout ', ' two occurrences'",
            "CALL errore( ' card_template ', ' two occurrences'",
            "K_POINTS automatic mesh: READ(input_line, *, END=10, ERR=20) nk1, nk2, nk3, k1, k2 ,k3",
            "K_POINTS automatic constraint: invalid offsets: must be 0 or 1",
            "K_POINTS automatic constraint: invalid values for nk1, nk2, nk3",
            "HUBBARD trap: misspelled/dash-less projector names abort with 'Wrong name of the Hubbard projectors'",
            "HUBBARD unknown option aborts with 'unknown option for HUBBARD'"
        );
    }
}
