/* GENERATED by scripts/thermo_pw_schema_miner.py - do not hand-edit.
 * Mined from the thermo_pw project (github.com/dalcorso/thermo_pw),
 * commit b73edd6d75b92df80f3a322279c6b12b301b9947 (fetched 2026-07-21),
 * src/thermo_readin.f90 sha256=3bca1fd8676d835c7204fb5f91ea7f8d4ac6e420e1ae98e4614607c5556977a5,
 * src/initialize_thermo_work.f90 sha256=9a27d2c76ec73175bcc8f12bc08a09e2a3d73267243b4f1d126010e7864a96a0.
 * Provenance rules: keyword set + group labels + procedural defaults come
 * from the NAMELIST declaration and the defaults section; the HARD accepted
 * values of `what` come from the part-1 SELECT CASE (TRIM(what)) whose
 * CASE DEFAULT calls errore('what not recognized'); the read path
 * (READ(iun_thermo, input_thermo...) -> errore) makes an unknown keyword
 * FATAL, mirrored as ERROR severity. Types are INFERRED from the default
 * literal when one is assigned (stated per entry), UNKNOWN otherwise. */
package quantumforge.input.schema;

import java.util.ArrayList;
import java.util.List;

/** Generated mined thermo_pw &INPUT_THERMO grammar table. */
final class QEThermoPwSchemaData {

    static List<QEThermoPwSchema.Entry> buildEntries() {
        List<QEThermoPwSchema.Entry> entries = new ArrayList<>();
        entries.add(QEThermoPwSchema.entry("what", QEThermoPwSchema.Type.CHARACTER, "' '", "declared before any group header"));
        entries.add(QEThermoPwSchema.entry("lgnuplot", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "gnuplot"));
        entries.add(QEThermoPwSchema.entry("gnuplot_command", QEThermoPwSchema.Type.CHARACTER, "'gnuplot'", "gnuplot"));
        entries.add(QEThermoPwSchema.entry("flgnuplot", QEThermoPwSchema.Type.CHARACTER, "'gnuplot.tmp'", "gnuplot"));
        entries.add(QEThermoPwSchema.entry("flext", QEThermoPwSchema.Type.CHARACTER, "'.ps'", "gnuplot"));
        entries.add(QEThermoPwSchema.entry("tmin", QEThermoPwSchema.Type.REAL, "1.0_DP", "temperature and pressure"));
        entries.add(QEThermoPwSchema.entry("tmax", QEThermoPwSchema.Type.REAL, "800.0_DP", "temperature and pressure"));
        entries.add(QEThermoPwSchema.entry("deltat", QEThermoPwSchema.Type.REAL, "3.0_DP", "temperature and pressure"));
        entries.add(QEThermoPwSchema.entry("ntemp", QEThermoPwSchema.Type.INTEGER, "1", "temperature and pressure"));
        entries.add(QEThermoPwSchema.entry("pressure", QEThermoPwSchema.Type.REAL, "0.0_DP", "temperature and pressure"));
        entries.add(QEThermoPwSchema.entry("continue_zero_ibrav", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "structure"));
        entries.add(QEThermoPwSchema.entry("find_ibrav", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "structure"));
        entries.add(QEThermoPwSchema.entry("nke", QEThermoPwSchema.Type.INTEGER, "5", "ke convergence"));
        entries.add(QEThermoPwSchema.entry("deltake", QEThermoPwSchema.Type.REAL, "10.0_DP", "ke convergence"));
        entries.add(QEThermoPwSchema.entry("nkeden", QEThermoPwSchema.Type.INTEGER, "1", "ke convergence"));
        entries.add(QEThermoPwSchema.entry("deltakeden", QEThermoPwSchema.Type.REAL, "100.0_DP", "ke convergence"));
        entries.add(QEThermoPwSchema.entry("flkeconv", QEThermoPwSchema.Type.CHARACTER, "'output_keconv.dat'", "ke convergence"));
        entries.add(QEThermoPwSchema.entry("flpskeconv", QEThermoPwSchema.Type.CHARACTER, "'output_keconv'", "ke convergence"));
        entries.add(QEThermoPwSchema.entry("nnk", QEThermoPwSchema.Type.INTEGER, "5", "nk convergence"));
        entries.add(QEThermoPwSchema.entry("deltank", QEThermoPwSchema.Type.INTEGER, "2", "nk convergence"));
        entries.add(QEThermoPwSchema.entry("nsigma", QEThermoPwSchema.Type.INTEGER, "1", "nk convergence"));
        entries.add(QEThermoPwSchema.entry("deltasigma", QEThermoPwSchema.Type.REAL, "0.005_DP", "nk convergence"));
        entries.add(QEThermoPwSchema.entry("flnkconv", QEThermoPwSchema.Type.CHARACTER, "'output_nkconv.dat'", "nk convergence"));
        entries.add(QEThermoPwSchema.entry("flpsnkconv", QEThermoPwSchema.Type.CHARACTER, "'output_nkconv'", "nk convergence"));
        entries.add(QEThermoPwSchema.entry("sigma_ry", QEThermoPwSchema.Type.REAL, "0.0_DP", "nk convergence"));
        entries.add(QEThermoPwSchema.entry("emin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("emax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("nbnd_bands", QEThermoPwSchema.Type.INTEGER, "0", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("lsym", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("only_bands_plot", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("enhance_plot", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("long_path", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("old_path", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("path_fact", QEThermoPwSchema.Type.REAL, "1.0_DP", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("q2d", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("is_a_path", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("q_in_band_form", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("q_in_cryst_coord", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("point_label_type", QEThermoPwSchema.Type.CHARACTER, "'SC'", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("filband", QEThermoPwSchema.Type.CHARACTER, "'output_band.dat'", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("flpband", QEThermoPwSchema.Type.CHARACTER, "'output_pband.dat'", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("flpsband", QEThermoPwSchema.Type.CHARACTER, "'output_band'", "scf_bands"));
        entries.add(QEThermoPwSchema.entry("lprojpbs", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("nkz", QEThermoPwSchema.Type.INTEGER, "1", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("gap_thr", QEThermoPwSchema.Type.REAL, "0.1_DP", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("sym_divide", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("identify_sur", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("force_bands", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("dump_states", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("sur_thr", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("sur_layers", QEThermoPwSchema.Type.INTEGER, "0", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("sp_min", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("subtract_vacuum", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("flpbs", QEThermoPwSchema.Type.CHARACTER, "'output_pbs'", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("flprojlayer", QEThermoPwSchema.Type.CHARACTER, "'output_projlayer'", "scf_2d_bands"));
        entries.add(QEThermoPwSchema.entry("deltae", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("ndose", QEThermoPwSchema.Type.INTEGER, "0", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("nk1_d", QEThermoPwSchema.Type.INTEGER, "16", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("nk2_d", QEThermoPwSchema.Type.INTEGER, "16", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("nk3_d", QEThermoPwSchema.Type.INTEGER, "16", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("k1_d", QEThermoPwSchema.Type.INTEGER, "1", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("k2_d", QEThermoPwSchema.Type.INTEGER, "1", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("k3_d", QEThermoPwSchema.Type.INTEGER, "1", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("sigmae", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("legauss", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("fleldos", QEThermoPwSchema.Type.CHARACTER, "'output_eldos.dat'", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("fleltherm", QEThermoPwSchema.Type.CHARACTER, "'output_eltherm.dat'", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("flpsdos", QEThermoPwSchema.Type.CHARACTER, "'output_dos'", "scf_dos,scf_disp"));
        entries.add(QEThermoPwSchema.entry("flpseltherm", QEThermoPwSchema.Type.CHARACTER, "'output_eltherm'", "scf_dos"));
        entries.add(QEThermoPwSchema.entry("lasymptote", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("flasy", QEThermoPwSchema.Type.CHARACTER, "'asy_tmp'", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("asymptote_command", QEThermoPwSchema.Type.CHARACTER, "'asy -f pdf -noprc'", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("npx", QEThermoPwSchema.Type.INTEGER, "8", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("lambda", QEThermoPwSchema.Type.REAL, "0.0_DP", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("lambda_elem", QEThermoPwSchema.Type.CHARACTER, "' '", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("flxrdp", QEThermoPwSchema.Type.CHARACTER, "'output_xrdp.dat'", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("flpsxrdp", QEThermoPwSchema.Type.CHARACTER, "'output_xrdp'", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("lxrdp", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("lformf", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("smin", QEThermoPwSchema.Type.REAL, "0.0_DP", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("smax", QEThermoPwSchema.Type.REAL, "1.0_DP", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("nspoint", QEThermoPwSchema.Type.INTEGER, "200", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("lcm", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("flformf", QEThermoPwSchema.Type.CHARACTER, "'output_formf.dat'", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("flpsformf", QEThermoPwSchema.Type.CHARACTER, "'output_formf'", "plot_bz"));
        entries.add(QEThermoPwSchema.entry("flepsilon", QEThermoPwSchema.Type.CHARACTER, "'epsilon'", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("flpsepsilon", QEThermoPwSchema.Type.CHARACTER, "'output_epsilon'", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("floptical", QEThermoPwSchema.Type.CHARACTER, "'optical'", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("flpsoptical", QEThermoPwSchema.Type.CHARACTER, "'output_optical'", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("force_band_calculation", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("many_k", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("memgpu", QEThermoPwSchema.Type.REAL, "10.0_DP", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("use_ph_images", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("sym_for_diago", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_ph"));
        entries.add(QEThermoPwSchema.entry("freqmin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("freqmax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("deltafreq", QEThermoPwSchema.Type.REAL, "1.0_DP", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("ndos_input", QEThermoPwSchema.Type.INTEGER, "1", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("nq1_d", QEThermoPwSchema.Type.INTEGER, "192", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("nq2_d", QEThermoPwSchema.Type.INTEGER, "192", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("nq3_d", QEThermoPwSchema.Type.INTEGER, "192", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("phdos_sigma", QEThermoPwSchema.Type.REAL, "2.0_DP", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("after_disp", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("fildyn", QEThermoPwSchema.Type.CHARACTER, "' '", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("zasr", QEThermoPwSchema.Type.CHARACTER, "'simple'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("ltherm_dos", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("ltherm_freq", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("flfrc", QEThermoPwSchema.Type.CHARACTER, "'output_frc.dat'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("flfrq", QEThermoPwSchema.Type.CHARACTER, "'output_frq.dat'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("fldos", QEThermoPwSchema.Type.CHARACTER, "'output_dos.dat'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("flvec", QEThermoPwSchema.Type.CHARACTER, "'matdyn.modes'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("fldosfrq", QEThermoPwSchema.Type.CHARACTER, "'save_frequencies.dat'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("fltherm", QEThermoPwSchema.Type.CHARACTER, "'output_therm.dat'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("flpsdisp", QEThermoPwSchema.Type.CHARACTER, "'output_disp'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("flpstherm", QEThermoPwSchema.Type.CHARACTER, "'output_therm'", "scf_disp"));
        entries.add(QEThermoPwSchema.entry("frozen_ions", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("ngeo_strain", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("elastic_algorithm", QEThermoPwSchema.Type.CHARACTER, "'standard'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("delta_epsilon", QEThermoPwSchema.Type.REAL, "0.005_DP", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("poly_degree", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("fl_el_cons", QEThermoPwSchema.Type.CHARACTER, "'output_el_cons.dat'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("fl_piezo", QEThermoPwSchema.Type.CHARACTER, "'output_piezo.dat'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("fl_piezom", QEThermoPwSchema.Type.CHARACTER, "'output_piezomag.dat'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("fl_magsusc", QEThermoPwSchema.Type.CHARACTER, "'output_mag_susc.dat'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("fl_magnetoelec", QEThermoPwSchema.Type.CHARACTER, "'output_magnetoelectric.dat'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("fl_dielectric", QEThermoPwSchema.Type.CHARACTER, "'output_dielectric.dat'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("fl_polar", QEThermoPwSchema.Type.CHARACTER, "'output_polar.dat'", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("lcm_ec", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("lzsisa", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("lfp", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("old_ec", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("stype", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("nmove", QEThermoPwSchema.Type.INTEGER, "5", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("move_at", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("atom_step", QEThermoPwSchema.Type.REAL, "0.02_DP", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("atom_dir", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("stypec", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("iconstr_internal_ec", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("nint_var_ec", QEThermoPwSchema.Type.INTEGER, "1", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("int_ngeo_ec", QEThermoPwSchema.Type.INTEGER, "5", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("int_step_ngeo_ec", QEThermoPwSchema.Type.REAL, "0.02_DP", "scf_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("nppl", QEThermoPwSchema.Type.INTEGER, "21", "scf_polarization"));
        entries.add(QEThermoPwSchema.entry("decompose_piezo", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_piezoelectric_tensor"));
        entries.add(QEThermoPwSchema.entry("doberry", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_piezoelectric_tensor"));
        entries.add(QEThermoPwSchema.entry("ngeo_b", QEThermoPwSchema.Type.INTEGER, "4", "scf_magnetic_susceptibility"));
        entries.add(QEThermoPwSchema.entry("delta_b", QEThermoPwSchema.Type.REAL, "0.0001", "scf_magnetic_susceptibility"));
        entries.add(QEThermoPwSchema.entry("dm", QEThermoPwSchema.Type.REAL, "0.005", "scf_magnetic_susceptibility"));
        entries.add(QEThermoPwSchema.entry("ngeo", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("step_ngeo", QEThermoPwSchema.Type.REAL, "0.5_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("ieos", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("lmurn", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("show_fit", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("vmin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("vmax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("deltav", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("pmin", QEThermoPwSchema.Type.REAL, "-50.0_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("pmax", QEThermoPwSchema.Type.REAL, "100.0_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("deltap", QEThermoPwSchema.Type.REAL, "5.0_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("npress_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("press_plot", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("nvol_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("ivol_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("nvol", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("lquartic", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("lsolve", QEThermoPwSchema.Type.INTEGER, "2", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("ltau_from_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc,mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("ltau_el_cons_from_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc,mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("save_distorted_energies", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("flevdat", QEThermoPwSchema.Type.CHARACTER, "'output_ev.dat'", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("flpsmur", QEThermoPwSchema.Type.CHARACTER, "'output_mur'", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("flps_el_cons", QEThermoPwSchema.Type.CHARACTER, "'output_elastic'", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("ncontours", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("flenergy", QEThermoPwSchema.Type.CHARACTER, "'output_energy'", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("flpsenergy", QEThermoPwSchema.Type.CHARACTER, "'output_energy'", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("lel_free_energy", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("hot_electrons", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc"));
        entries.add(QEThermoPwSchema.entry("do_scf_relax", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_elastic_constants"));
        entries.add(QEThermoPwSchema.entry("grunmin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("grunmax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("volume_ph", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("celldm_ph", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("temp_ph", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("with_eigen", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("only_anhar", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("ntemp_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("temp_plot", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("poly_degree_ph", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("poly_degree_thermo", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("poly_degree_bfact", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("poly_degree_elc", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("lv0_t", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("lb0_t", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("idebye", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("noelcvg", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("linternal_thermo", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("iconstr_internal", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("nint_var", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("int_ngeo", QEThermoPwSchema.Type.INTEGER, "5", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("int_step_ngeo", QEThermoPwSchema.Type.REAL, "0.005", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("linterpolate_tau", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("add_empirical", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("efe", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("alpha1", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("alpha2", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("v0p", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("ltherm_glob", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("lgruneisen_gen", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("ggrun_recipe", QEThermoPwSchema.Type.INTEGER, "2", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("icenter_grun", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("njump", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("lhugoniot", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("lgeo_from_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("lgeo_to_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("poly_degree_grun", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("flpgrun", QEThermoPwSchema.Type.CHARACTER, "'output_pgrun.dat'", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("flgrun", QEThermoPwSchema.Type.CHARACTER, "'output_grun.dat'", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("flpsgrun", QEThermoPwSchema.Type.CHARACTER, "'output_grun'", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("flanhar", QEThermoPwSchema.Type.CHARACTER, "'output_anhar.dat'", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("flelanhar", QEThermoPwSchema.Type.CHARACTER, "'output_elanhar.dat'", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("flpsanhar", QEThermoPwSchema.Type.CHARACTER, "'output_anhar'", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("flgeom", QEThermoPwSchema.Type.CHARACTER, "'output_geometry'", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("fact_ngeo", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("ngeo_ph", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("all_geometries_together", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t"));
        entries.add(QEThermoPwSchema.entry("use_free_energy", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "elastic_constants_geo"));
        entries.add(QEThermoPwSchema.entry("start_geometry_qha", QEThermoPwSchema.Type.INTEGER, "1", "elastic_constants_geo"));
        entries.add(QEThermoPwSchema.entry("last_geometry_qha", QEThermoPwSchema.Type.INTEGER, "1000000", "elastic_constants_geo"));
        entries.add(QEThermoPwSchema.entry("omega_group", QEThermoPwSchema.Type.INTEGER, "1", "optical"));
        entries.add(QEThermoPwSchema.entry("max_geometries", QEThermoPwSchema.Type.INTEGER, "1000000", "recover features"));
        entries.add(QEThermoPwSchema.entry("start_geometry", QEThermoPwSchema.Type.INTEGER, "1", "recover features"));
        entries.add(QEThermoPwSchema.entry("last_geometry", QEThermoPwSchema.Type.INTEGER, "1000000", "recover features"));
        entries.add(QEThermoPwSchema.entry("max_seconds", QEThermoPwSchema.Type.REAL, "1.D8", "recover features"));
        return entries;
    }

    /** HARD accepted literals of `what` (CASE DEFAULT -> errore). */
    static List<String> buildWhatAcceptedValues() {
        return List.of("plot_bz", "scf", "scf_bands", "scf_2d_bands", "scf_dos", "scf_ph", "scf_disp", "scf_ke", "scf_nk", "scf_elastic_constants", "scf_piezoelectric_tensor", "scf_piezomagnetic_tensor", "scf_polarization", "scf_magnetic_susceptibility", "scf_magnetoelectric_tensor", "mur_lc", "mur_lc_bands", "mur_lc_dos", "mur_lc_ph", "mur_lc_disp", "mur_lc_elastic_constants", "mur_lc_piezoelectric_tensor", "mur_lc_piezomagnetic_tensor", "mur_lc_polarization", "mur_lc_magnetic_susceptibility", "mur_lc_magnetoelectric_tensor", "mur_lc_t", "elastic_constants_geo", "piezoelectric_tensor_geo", "polarization_geo");
    }

    /** Verbatim consistency-check fact lines from thermo_readin. */
    static List<String> buildConsistencyFacts() {
        return List.of(
            "IF (what==' ') CALL errore('thermo_readin','''what'' must be initialized',1)",
            "CALL errore('thermo_readin','all_geometries_together requires mur_lc_t or elastic_constants_geo',1)",
            "CALL errore('thermo_readin','all_geometries_together not compatible with max_geometries',1)",
            "IF (nsigma > max_sigma) CALL errore('thermo_readin','nsigma too large', 1)",
            "IF (lgruneisen_gen .AND. lmurn) CALL errore('thermo_readin', 'lgruneisen_gen requires lmurn=.FALSE.',1)",
            "CALL errore('thermo_readin', 'lgruneisen_gen requires what=''mur_lc_t''',1)",
            "IF (npress_plot> max_opt) CALL errore('thermo_readin', 'npress_plot too large',1)",
            "IF (ntemp_plot> max_opt) CALL errore('thermo_readin', 'ntemp_plot too large',1)",
            "CALL errore('thermo_readin','wrong nvol_plot',1)",
            "CALL errore('thermo_readin','many_k requires nproc=npool',1)",
            "IF (ierr /= 0) CALL errore('thermo_readin', 'cannot get device count', ierr)",
            "CALL errore('thermo_readin','wrong equation of state (ieos)',1)",
            "CALL errore('thermo_readin','poly_degree_ph must be between 1 and 4',1)",
            "CALL errore('thermo_readin','poly_degree_thermo must be between 1 and 4',1)",
            "CALL errore('thermo_readin','poly_degree_bfact must be between 1 and 4',1)",
            "CALL errore('thermo_readin','poly_degree_elc must be between 1 and 4',1)",
            "CALL errore('thermo_readin','linterpolate_tau requires a constraint',1)",
            "CALL errore('thermo_readin','decompose piezo but no constraint',1)",
            "CALL errore('thermo_readin','decompose piezo requires frozen_ions=.FALSE.',1)",
            "CALL errore('thermo_readin','linterpolate_tau and linternal_thermo cannot be both .TRUE.',1)",
            "CALL errore('thermo_readin','Unrecognized elastic algorithm',1)",
            "CALL errore('thermo_readin','Only the energy algorithms are available in this case',1)",
            "CALL errore('thermo_readin','Use stypec for internal coordinates',1)",
            "CALL errore('thermo_readin','stype requires an energy algorithm',1)"
        );
    }
}
