/* GENERATED by scripts/thermo_pw_schema_miner.py - do not hand-edit.
 * Mined from the thermo_pw project (github.com/dalcorso/thermo_pw) at
 * window 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1 + master commit b73edd6d75b92df80f3a322279c6b12b301b9947,
 * 2.0.0: thermo_readin sha256=d698094c6b397a6355240479d2f615d512dab15bcfdfc0d56306592e68f423c3,
 *        initialize_thermo_work sha256=d5e73707a6ea769db248f65fa19732f21d6fa664619762fcc9dffcfd19b4057c,
 * 2.0.1: thermo_readin sha256=12b5cd5345b0ca2a8aa2439dd33662acb64ac4a42e3f28020d73ab6101d9c884,
 *        initialize_thermo_work sha256=95ca811d87ef3d49164ff92879be8a222f06cbe962a85d5d2efaba640213d9f5,
 * 2.0.2: thermo_readin sha256=12b5cd5345b0ca2a8aa2439dd33662acb64ac4a42e3f28020d73ab6101d9c884,
 *        initialize_thermo_work sha256=95ca811d87ef3d49164ff92879be8a222f06cbe962a85d5d2efaba640213d9f5,
 * 2.0.3: thermo_readin sha256=12b5cd5345b0ca2a8aa2439dd33662acb64ac4a42e3f28020d73ab6101d9c884,
 *        initialize_thermo_work sha256=95ca811d87ef3d49164ff92879be8a222f06cbe962a85d5d2efaba640213d9f5,
 * 2.1.0: thermo_readin sha256=703ad9502a60e8eaa76b827a7d3a571e6d5f24969e773a5a28cc89cfdd93dd69,
 *        initialize_thermo_work sha256=ac3c18fa77ee45f909f242678f0685a96fda87899483d6c34c213c25880c4dc8,
 * 2.1.1: thermo_readin sha256=703ad9502a60e8eaa76b827a7d3a571e6d5f24969e773a5a28cc89cfdd93dd69,
 *        initialize_thermo_work sha256=ac3c18fa77ee45f909f242678f0685a96fda87899483d6c34c213c25880c4dc8,
 * master: thermo_readin sha256=3bca1fd8676d835c7204fb5f91ea7f8d4ac6e420e1ae98e4614607c5556977a5,
 *         initialize_thermo_work sha256=9a27d2c76ec73175bcc8f12bc08a09e2a3d73267243b4f1d126010e7864a96a0,
 * extracted 2026-07-21 from release tags + the pinned master commit.
 * Provenance rules: keyword set + group labels + procedural defaults come
 * from the NAMELIST declaration and the defaults section of thermo_readin.f90;
 * the HARD accepted values of `what` come from the part-1 SELECT CASE
 * (TRIM(what)) whose CASE DEFAULT calls errore('what not recognized'); the
 * read path (READ(iun_thermo, input_thermo...) -> errore) makes an unknown
 * keyword FATAL, mirrored as ERROR severity. Presence masks are 7-bit, bit i
 * = window index i (newest = master). Types/defaults are the NEWEST reading;
 * per-tag deviations ride in the drift column verbatim (INFERRED types). */
package quantumforge.input.schema;

import java.util.ArrayList;
import java.util.List;

/** Generated mined thermo_pw &INPUT_THERMO grammar table (version window). */
final class QEThermoPwSchemaData {

    static List<QEThermoPwSchema.Entry> buildEntries() {
        List<QEThermoPwSchema.Entry> entries = new ArrayList<>();
        entries.add(QEThermoPwSchema.entry("what", QEThermoPwSchema.Type.CHARACTER, "' '", "declared before any group header", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lgnuplot", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "gnuplot", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("gnuplot_command", QEThermoPwSchema.Type.CHARACTER, "'gnuplot'", "gnuplot", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flgnuplot", QEThermoPwSchema.Type.CHARACTER, "'gnuplot.tmp'", "gnuplot", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flext", QEThermoPwSchema.Type.CHARACTER, "'.ps'", "gnuplot", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("tmin", QEThermoPwSchema.Type.REAL, "1.0_DP", "temperature and pressure", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("tmax", QEThermoPwSchema.Type.REAL, "800.0_DP", "temperature and pressure", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltat", QEThermoPwSchema.Type.REAL, "3.0_DP", "temperature and pressure", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ntemp", QEThermoPwSchema.Type.INTEGER, "1", "temperature and pressure", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("pressure", QEThermoPwSchema.Type.REAL, "0.0_DP", "temperature and pressure", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("continue_zero_ibrav", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "structure", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("find_ibrav", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "structure", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nke", QEThermoPwSchema.Type.INTEGER, "5", "ke convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltake", QEThermoPwSchema.Type.REAL, "10.0_DP", "ke convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nkeden", QEThermoPwSchema.Type.INTEGER, "1", "ke convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltakeden", QEThermoPwSchema.Type.REAL, "100.0_DP", "ke convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flkeconv", QEThermoPwSchema.Type.CHARACTER, "'output_keconv.dat'", "ke convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpskeconv", QEThermoPwSchema.Type.CHARACTER, "'output_keconv'", "ke convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nnk", QEThermoPwSchema.Type.INTEGER, "5", "nk convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltank", QEThermoPwSchema.Type.INTEGER, "2", "nk convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nsigma", QEThermoPwSchema.Type.INTEGER, "1", "nk convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltasigma", QEThermoPwSchema.Type.REAL, "0.005_DP", "nk convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flnkconv", QEThermoPwSchema.Type.CHARACTER, "'output_nkconv.dat'", "nk convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsnkconv", QEThermoPwSchema.Type.CHARACTER, "'output_nkconv'", "nk convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("sigma_ry", QEThermoPwSchema.Type.REAL, "0.0_DP", "nk convergence", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("emin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("emax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nbnd_bands", QEThermoPwSchema.Type.INTEGER, "0", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lsym", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("only_bands_plot", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("enhance_plot", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("long_path", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("old_path", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("path_fact", QEThermoPwSchema.Type.REAL, "1.0_DP", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("q2d", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("is_a_path", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("q_in_band_form", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("q_in_cryst_coord", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("point_label_type", QEThermoPwSchema.Type.CHARACTER, "'SC'", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("filband", QEThermoPwSchema.Type.CHARACTER, "'output_band.dat'", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpband", QEThermoPwSchema.Type.CHARACTER, "'output_pband.dat'", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsband", QEThermoPwSchema.Type.CHARACTER, "'output_band'", "scf_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lprojpbs", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nkz", QEThermoPwSchema.Type.INTEGER, "1", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("gap_thr", QEThermoPwSchema.Type.REAL, "0.1_DP", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("sym_divide", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("identify_sur", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("force_bands", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("dump_states", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("sur_thr", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("sur_layers", QEThermoPwSchema.Type.INTEGER, "0", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("sp_min", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("subtract_vacuum", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpbs", QEThermoPwSchema.Type.CHARACTER, "'output_pbs'", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flprojlayer", QEThermoPwSchema.Type.CHARACTER, "'output_projlayer'", "scf_2d_bands", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltae", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ndose", QEThermoPwSchema.Type.INTEGER, "0", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nk1_d", QEThermoPwSchema.Type.INTEGER, "16", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nk2_d", QEThermoPwSchema.Type.INTEGER, "16", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nk3_d", QEThermoPwSchema.Type.INTEGER, "16", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("k1_d", QEThermoPwSchema.Type.INTEGER, "1", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("k2_d", QEThermoPwSchema.Type.INTEGER, "1", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("k3_d", QEThermoPwSchema.Type.INTEGER, "1", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("sigmae", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("legauss", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fleldos", QEThermoPwSchema.Type.CHARACTER, "'output_eldos.dat'", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fleltherm", QEThermoPwSchema.Type.CHARACTER, "'output_eltherm.dat'", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsdos", QEThermoPwSchema.Type.CHARACTER, "'output_dos'", "scf_dos,scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpseltherm", QEThermoPwSchema.Type.CHARACTER, "'output_eltherm'", "scf_dos", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lasymptote", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flasy", QEThermoPwSchema.Type.CHARACTER, "'asy_tmp'", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("asymptote_command", QEThermoPwSchema.Type.CHARACTER, "'asy -f pdf -noprc'", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("npx", QEThermoPwSchema.Type.INTEGER, "8", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lambda", QEThermoPwSchema.Type.REAL, "0.0_DP", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lambda_elem", QEThermoPwSchema.Type.CHARACTER, "' '", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flxrdp", QEThermoPwSchema.Type.CHARACTER, "'output_xrdp.dat'", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsxrdp", QEThermoPwSchema.Type.CHARACTER, "'output_xrdp'", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lxrdp", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lformf", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("smin", QEThermoPwSchema.Type.REAL, "0.0_DP", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("smax", QEThermoPwSchema.Type.REAL, "1.0_DP", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nspoint", QEThermoPwSchema.Type.INTEGER, "200", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lcm", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flformf", QEThermoPwSchema.Type.CHARACTER, "'output_formf.dat'", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsformf", QEThermoPwSchema.Type.CHARACTER, "'output_formf'", "plot_bz", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flepsilon", QEThermoPwSchema.Type.CHARACTER, "'epsilon'", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsepsilon", QEThermoPwSchema.Type.CHARACTER, "'output_epsilon'", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("floptical", QEThermoPwSchema.Type.CHARACTER, "'optical'", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsoptical", QEThermoPwSchema.Type.CHARACTER, "'output_optical'", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("force_band_calculation", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("many_k", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("memgpu", QEThermoPwSchema.Type.REAL, "10.0_DP", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("use_ph_images", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("sym_for_diago", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_ph", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("freqmin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("freqmax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltafreq", QEThermoPwSchema.Type.REAL, "1.0_DP", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ndos_input", QEThermoPwSchema.Type.INTEGER, "1", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nq1_d", QEThermoPwSchema.Type.INTEGER, "192", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nq2_d", QEThermoPwSchema.Type.INTEGER, "192", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nq3_d", QEThermoPwSchema.Type.INTEGER, "192", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("phdos_sigma", QEThermoPwSchema.Type.REAL, "2.0_DP", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("after_disp", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fildyn", QEThermoPwSchema.Type.CHARACTER, "' '", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("zasr", QEThermoPwSchema.Type.CHARACTER, "'simple'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ltherm_dos", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ltherm_freq", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flfrc", QEThermoPwSchema.Type.CHARACTER, "'output_frc.dat'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flfrq", QEThermoPwSchema.Type.CHARACTER, "'output_frq.dat'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fldos", QEThermoPwSchema.Type.CHARACTER, "'output_dos.dat'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flvec", QEThermoPwSchema.Type.CHARACTER, "'matdyn.modes'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fldosfrq", QEThermoPwSchema.Type.CHARACTER, "'save_frequencies.dat'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fltherm", QEThermoPwSchema.Type.CHARACTER, "'output_therm.dat'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsdisp", QEThermoPwSchema.Type.CHARACTER, "'output_disp'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpstherm", QEThermoPwSchema.Type.CHARACTER, "'output_therm'", "scf_disp", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("frozen_ions", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ngeo_strain", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("elastic_algorithm", QEThermoPwSchema.Type.CHARACTER, "'standard'", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("delta_epsilon", QEThermoPwSchema.Type.REAL, "0.005_DP", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("poly_degree", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fl_el_cons", QEThermoPwSchema.Type.CHARACTER, "'output_el_cons.dat'", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fl_piezo", QEThermoPwSchema.Type.CHARACTER, "'output_piezo.dat'", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("fl_piezom", QEThermoPwSchema.Type.CHARACTER, "'output_piezomag.dat'", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("fl_magsusc", QEThermoPwSchema.Type.CHARACTER, "'output_mag_susc.dat'", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("fl_magnetoelec", QEThermoPwSchema.Type.CHARACTER, "'output_magnetoelectric.dat'", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("fl_dielectric", QEThermoPwSchema.Type.CHARACTER, "'output_dielectric.dat'", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("fl_polar", QEThermoPwSchema.Type.CHARACTER, "'output_polar.dat'", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("lcm_ec", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lzsisa", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lfp", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("old_ec", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants", 0x7F, "2.0.0:LOGICAL:.TRUE."));
        entries.add(QEThermoPwSchema.entry("stype", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nmove", QEThermoPwSchema.Type.INTEGER, "5", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("move_at", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("atom_step", QEThermoPwSchema.Type.REAL, "0.02_DP", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("atom_dir", QEThermoPwSchema.Type.REAL, "0.0_DP", "scf_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("stypec", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("iconstr_internal_ec", QEThermoPwSchema.Type.INTEGER, "0", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("nint_var_ec", QEThermoPwSchema.Type.INTEGER, "1", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("int_ngeo_ec", QEThermoPwSchema.Type.INTEGER, "5", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("int_step_ngeo_ec", QEThermoPwSchema.Type.REAL, "0.02_DP", "scf_elastic_constants", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("nppl", QEThermoPwSchema.Type.INTEGER, "21", "scf_polarization", 0x7F, "2.0.0:INTEGER:51,2.0.1:INTEGER:51,2.0.2:INTEGER:51,2.0.3:INTEGER:51,2.1.0:INTEGER:51,2.1.1:INTEGER:51"));
        entries.add(QEThermoPwSchema.entry("decompose_piezo", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "scf_piezoelectric_tensor", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("doberry", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "scf_piezoelectric_tensor", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("ngeo_b", QEThermoPwSchema.Type.INTEGER, "4", "scf_magnetic_susceptibility", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("delta_b", QEThermoPwSchema.Type.REAL, "0.0001", "scf_magnetic_susceptibility", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("dm", QEThermoPwSchema.Type.REAL, "0.005", "scf_magnetic_susceptibility", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("ngeo", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("step_ngeo", QEThermoPwSchema.Type.REAL, "0.5_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ieos", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lmurn", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("show_fit", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("vmin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("vmax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltav", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("pmin", QEThermoPwSchema.Type.REAL, "-50.0_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("pmax", QEThermoPwSchema.Type.REAL, "100.0_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("deltap", QEThermoPwSchema.Type.REAL, "5.0_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("npress_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("press_plot", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nvol_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ivol_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("nvol", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lquartic", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lsolve", QEThermoPwSchema.Type.INTEGER, "2", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ltau_from_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc,mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("ltau_el_cons_from_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc,mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("save_distorted_energies", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("flevdat", QEThermoPwSchema.Type.CHARACTER, "'output_ev.dat'", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsmur", QEThermoPwSchema.Type.CHARACTER, "'output_mur'", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flps_el_cons", QEThermoPwSchema.Type.CHARACTER, "'output_elastic'", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ncontours", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flenergy", QEThermoPwSchema.Type.CHARACTER, "'output_energy'", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsenergy", QEThermoPwSchema.Type.CHARACTER, "'output_energy'", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lel_free_energy", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("hot_electrons", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("do_scf_relax", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_elastic_constants", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("grunmin_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("grunmax_input", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("volume_ph", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("celldm_ph", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("temp_ph", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("with_eigen", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("only_anhar", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("ntemp_plot", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("temp_plot", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("poly_degree_ph", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("poly_degree_thermo", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("poly_degree_bfact", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("poly_degree_elc", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lv0_t", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lb0_t", QEThermoPwSchema.Type.LOGICAL, ".TRUE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("idebye", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("noelcvg", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("linternal_thermo", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("iconstr_internal", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("nint_var", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("int_ngeo", QEThermoPwSchema.Type.INTEGER, "5", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("int_step_ngeo", QEThermoPwSchema.Type.REAL, "0.005", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("linterpolate_tau", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("add_empirical", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("efe", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("alpha1", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("alpha2", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("v0p", QEThermoPwSchema.Type.REAL, "0.0_DP", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ltherm_glob", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lgruneisen_gen", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x70, ""));
        entries.add(QEThermoPwSchema.entry("ggrun_recipe", QEThermoPwSchema.Type.INTEGER, "2", "mur_lc_t", 0x70, ""));
        entries.add(QEThermoPwSchema.entry("icenter_grun", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t", 0x70, ""));
        entries.add(QEThermoPwSchema.entry("njump", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc_t", 0x40, ""));
        entries.add(QEThermoPwSchema.entry("lhugoniot", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lgeo_from_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("lgeo_to_file", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("poly_degree_grun", QEThermoPwSchema.Type.INTEGER, "4", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpgrun", QEThermoPwSchema.Type.CHARACTER, "'output_pgrun.dat'", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flgrun", QEThermoPwSchema.Type.CHARACTER, "'output_grun.dat'", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsgrun", QEThermoPwSchema.Type.CHARACTER, "'output_grun'", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flanhar", QEThermoPwSchema.Type.CHARACTER, "'output_anhar.dat'", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flelanhar", QEThermoPwSchema.Type.CHARACTER, "'output_elanhar.dat'", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flpsanhar", QEThermoPwSchema.Type.CHARACTER, "'output_anhar'", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("flgeom", QEThermoPwSchema.Type.CHARACTER, "'output_geometry'", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("fact_ngeo", QEThermoPwSchema.Type.INTEGER, "1", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("ngeo_ph", QEThermoPwSchema.Type.INTEGER, "0", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("all_geometries_together", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "mur_lc_t", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("use_free_energy", QEThermoPwSchema.Type.LOGICAL, ".FALSE.", "elastic_constants_geo", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("start_geometry_qha", QEThermoPwSchema.Type.INTEGER, "1", "elastic_constants_geo", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("last_geometry_qha", QEThermoPwSchema.Type.INTEGER, "1000000", "elastic_constants_geo", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("omega_group", QEThermoPwSchema.Type.INTEGER, "1", "optical", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("max_geometries", QEThermoPwSchema.Type.INTEGER, "1000000", "recover features", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("start_geometry", QEThermoPwSchema.Type.INTEGER, "1", "recover features", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("last_geometry", QEThermoPwSchema.Type.INTEGER, "1000000", "recover features", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("max_seconds", QEThermoPwSchema.Type.REAL, "1.D8", "recover features", 0x7F, ""));
        entries.add(QEThermoPwSchema.entry("epsilon_0", QEThermoPwSchema.Type.UNKNOWN, null, "scf_elastic_constants", 0x3F, "2.0.0:REAL:0.0_DP,2.0.1:REAL:0.0_DP,2.0.2:REAL:0.0_DP,2.0.3:REAL:0.0_DP,2.1.0:REAL:0.0_DP"));
        entries.add(QEThermoPwSchema.entry("reduced_grid", QEThermoPwSchema.Type.UNKNOWN, null, "mur_lc", 0x3F, "2.0.0:LOGICAL:.FALSE.,2.0.1:LOGICAL:.FALSE.,2.0.2:LOGICAL:.FALSE.,2.0.3:LOGICAL:.FALSE.,2.1.0:LOGICAL:.FALSE."));
        return entries;
    }

    /** HARD accepted literals of `what` with presence masks (CASE DEFAULT -> errore). */
    static List<String> buildWhatAcceptedValues() {
        return List.of("plot_bz~0x7F", "scf~0x7F", "scf_bands~0x7F", "scf_2d_bands~0x7F", "scf_dos~0x7F", "scf_ph~0x7F", "scf_disp~0x7F", "scf_ke~0x7F", "scf_nk~0x7F", "scf_elastic_constants~0x7F", "scf_piezoelectric_tensor~0x7F", "scf_polarization~0x7F", "mur_lc~0x7F", "mur_lc_bands~0x7F", "mur_lc_dos~0x7F", "mur_lc_ph~0x7F", "mur_lc_disp~0x7F", "mur_lc_elastic_constants~0x7F", "mur_lc_piezoelectric_tensor~0x7F", "mur_lc_polarization~0x7F", "mur_lc_t~0x7F", "elastic_constants_geo~0x7F", "scf_piezomagnetic_tensor~0x40", "scf_magnetic_susceptibility~0x40", "scf_magnetoelectric_tensor~0x40", "mur_lc_piezomagnetic_tensor~0x40", "mur_lc_magnetic_susceptibility~0x40", "mur_lc_magnetoelectric_tensor~0x40", "piezoelectric_tensor_geo~0x40", "polarization_geo~0x40");
    }

    /** Verbatim consistency-check fact lines with presence masks. */
    static List<String> buildConsistencyFacts() {
        return List.of(
            "IF (what==' ') CALL errore('thermo_readin','''what'' must be initialized',1)" + "~0x7F",
            "CALL errore('thermo_readin','all_geometries_together requires mur_lc_t or elastic_constants_geo',1)" + "~0x7F",
            "CALL errore('thermo_readin','all_geometries_together not compatible with max_geometries',1)" + "~0x7F",
            "IF (nsigma > max_sigma) CALL errore('thermo_readin','nsigma too large', 1)" + "~0x7F",
            "IF (lmurn.AND.reduced_grid) CALL errore('thermo_readin', 'lmurn and reduced_grid cannot be both .TRUE.',1)" + "~0x3F",
            "IF (npress_plot> max_opt) CALL errore('thermo_readin', 'npress_plot too large',1)" + "~0x7F",
            "IF (ntemp_plot> max_opt) CALL errore('thermo_readin', 'ntemp_plot too large',1)" + "~0x7F",
            "CALL errore('thermo_readin','wrong nvol_plot',1)" + "~0x7F",
            "CALL errore('thermo_readin','many_k requires nproc=npool',1)" + "~0x7F",
            "IF (ierr /= 0) CALL errore('thermo_readin', 'cannot get device count', ierr)" + "~0x7F",
            "CALL errore('thermo_readin','many_k requires as many GPU as CPU',1)" + "~0x0F",
            "CALL errore('thermo_readin','wrong equation of state (ieos)',1)" + "~0x7F",
            "CALL errore('thermo_readin','poly_degree_ph must be between 1 and 4',1)" + "~0x7F",
            "CALL errore('thermo_readin','poly_degree_thermo must be between 1 and 4',1)" + "~0x7F",
            "CALL errore('thermo_readin','poly_degree_bfact must be between 1 and 4',1)" + "~0x7F",
            "CALL errore('thermo_readin','poly_degree_elc must be between 1 and 4',1)" + "~0x7F",
            "CALL errore('thermo_readin','Unrecognized elastic algorithm',1)" + "~0x7F",
            "CALL errore('thermo_readin','Only the energy algorithms are available in this case',1)" + "~0x7F",
            "CALL errore('thermo_readin','stype requires an energy algorithm',1)" + "~0x7F",
            "CALL errore('thermo_readin','lzsisa and lfp are mutually exclusive',1)" + "~0x3F",
            "IF (tend) CALL errore('thermo_readin','Missing lines',1)" + "~0x3F",
            "IF (terr) CALL errore('thermo_readin','Error reading q points',1)" + "~0x3F",
            "50 IF (ios /=0) CALL errore('thermo_readin', 'problem reading number of points',1)" + "~0x3F",
            "CALL errore('thermo_readin','Creating input files',ios)" + "~0x0F",
            "IF (lgruneisen_gen .AND. lmurn) CALL errore('thermo_readin', 'lgruneisen_gen requires lmurn=.FALSE.',1)" + "~0x70",
            "CALL errore('thermo_readin', 'lgruneisen_gen requires what=''mur_lc_t''',1)" + "~0x70",
            "CALL errore('thermo_readin','linterpolate_tau requires a constraint',1)" + "~0x40",
            "CALL errore('thermo_readin','decompose piezo but no constraint',1)" + "~0x40",
            "CALL errore('thermo_readin','decompose piezo requires frozen_ions=.FALSE.',1)" + "~0x40",
            "CALL errore('thermo_readin','linterpolate_tau and linternal_thermo cannot be both .TRUE.',1)" + "~0x40",
            "CALL errore('thermo_readin','Use stypec for internal coordinates',1)" + "~0x40"
        );
    }
}
