/* Copyright (C) 2025-2026 QuantumForge Development Team.
 */
package quantumforge.input.validation;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import quantumforge.operation.OperationResult;

/**
 * Batch 173 (roadmap #111, VASP input side): the KPOINTS grammar, pinned
 * from the vasp.at wiki 'KPOINTS' page (fetched 2026-07-22) covering ALL
 * FOUR documented modes:
 *
 * <ul>
 *   <li><b>Regular mesh</b> (AUTO mode): comment line; second line 0;
 *       third line whose first nonblank character is {@code G/g}
 *       (Gamma-centered) or {@code M/m} (Monkhorst-Pack); fourth line the
 *       subdivisions N1 N2 N3; an optional fifth line shift s1 s2 s3.</li>
 *   <li><b>Generalized regular mesh</b>: third line first character
 *       {@code C/c/K/k} (Cartesian) or {@code R/r} (reciprocal) selects the
 *       coordinate system, followed by THREE generating-vector lines and
 *       one shift line; 'The generating vectors g1, g2, and g3 must be
 *       commensurate with the reciprocal lattice. This means b_i = sum_j
 *       M_ij g_j where the matrix M contains only integer entries' (wiki
 *       verbatim Important block). An uninterpretable third-line character
 *       falls back to reciprocal - the wiki itself says 'we recommend not
 *       relying on this behavior', so the deck surfaces a WARNING note.</li>
 *   <li><b>Line mode</b> (band paths): third line first character
 *       {@code L/l}; fourth line the coordinate system (C/c/K/k =
 *       Cartesian, anything else fractional); then vertex pairs (3 reals +
 *       optional label; blank lines tolerated); the second line is the
 *       number of points PER SEGMENT. The wiki warnings are carried
 *       verbatim: 'The mesh generated by this mode is not suitable for
 *       self-consistent calculations. Please set ICHARG = 11 to avoid
 *       updating the density.' and 'For meta-GGA and hybrid functionals, a
 *       regular mesh must always be provided.' Endpoints ARE included per
 *       segment (the wiki's own 'two X and W points' remark).</li>
 *   <li><b>Explicit list</b>: count&gt;0 with a non-L third line (C/c/K/k
 *       Cartesian, else fractional); exactly count lines of x y z weight;
 *       'VASP takes care that weights are properly normalized' (verbatim
 *       note). An optional tetrahedra block follows (a line starting with
 *       T/t, then 'ntet volumeWeight', then ntet rows of
 *       degeneracy + four 1-based corner indices) with the wiki warning
 *       'VASP does not renormalize the weights of the tetrahedra.'</li>
 * </ul>
 *
 * <p>Refusals are typed (VASP_KPOINTS_INPUT/EMPTY/SHAPE) and bounded
 * (512 KiB / 200k points). Notes/warnings travel with the deck; the
 * canonical {@link #toKpointsText()} writer plus the factories make the
 * round-trip provable. Nothing executes VASP; KSPACING (INCAR route) and
 * KPOINTS_OPT are mentioned by the wiki and stated in the javadoc, never
 * conflated with this file.</p>
 */
public final class VaspKpointsDeck {

    /** The four pinned generation modes. */
    public enum Mode { AUTO_GAMMA, AUTO_MP, AUTO_GENERALIZED, LINE_MODE, EXPLICIT }

    /** One line-mode vertex (3 coords + optional label, per the wiki template). */
    public static final record Vertex(double x, double y, double z, String label) { }

    /** One explicit k-point (3 coords + weight). */
    public static final record ExplicitPoint(double x, double y, double z, double weight) { }

    /** One tetrahedron row (degeneration weight + 1-based corner indices). */
    public static final record Tetra(int degeneracy, int c1, int c2, int c3, int c4) { }

    private final String comment;
    private final Mode mode;
    private final boolean cartesian;
    private final int[] subdivisions;      // AUTO_GAMMA/AUTO_MP: N1 N2 N3
    private final double[] shift;          // optional mesh shift (3 doubles)
    private final double[][] generators;   // AUTO_GENERALIZED: 3x3
    private final int pointsPerSegment;    // LINE_MODE
    private final List<Vertex> vertices;   // LINE_MODE (pairs = segments)
    private final List<ExplicitPoint> points; // EXPLICIT
    private final List<Tetra> tetras;      // optional tetrahedra block
    private final List<String> notes;

    private VaspKpointsDeck(String comment, Mode mode, boolean cartesian,
            int[] subdivisions, double[] shift, double[][] generators,
            int pointsPerSegment, List<Vertex> vertices,
            List<ExplicitPoint> points, List<Tetra> tetras, List<String> notes) {
        this.comment = comment;
        this.mode = mode;
        this.cartesian = cartesian;
        this.subdivisions = subdivisions;
        this.shift = shift;
        this.generators = generators;
        this.pointsPerSegment = pointsPerSegment;
        this.vertices = vertices;
        this.points = points;
        this.tetras = tetras;
        this.notes = notes;
    }

    public String getComment() { return this.comment; }
    public Mode getMode() { return this.mode; }
    public boolean isCartesian() { return this.cartesian; }
    /** [N1,N2,N3] for AUTO_GAMMA/AUTO_MP, else empty. */
    public int[] getSubdivisions() { return this.subdivisions.clone(); }
    /** [s1,s2,s3] or empty when the file omitted the shift line. */
    public double[] getShift() { return this.shift.clone(); }
    /** Generating vectors for AUTO_GENERALIZED (rows g1,g2,g3), else empty. */
    public double[][] getGenerators() {
        double[][] copy = new double[this.generators.length][];
        for (int i = 0; i < copy.length; i++) {
            copy[i] = this.generators[i].clone();
        }
        return copy;
    }
    public int getPointsPerSegment() { return this.pointsPerSegment; }
    public List<Vertex> getVertices() { return this.vertices; }
    public List<ExplicitPoint> getPoints() { return this.points; }
    public List<Tetra> getTetras() { return this.tetras; }
    /** Warnings/notes recorded while reading (verbatim wiki quotes inside). */
    public List<String> getNotes() { return this.notes; }

    // ================================ parse ================================

    /** Bounded parse; VASP_KPOINTS_INPUT/EMPTY/SHAPE/OK. */
    public static OperationResult<VaspKpointsDeck> parse(String text) {
        if (text == null) {
            return OperationResult.failed("VASP_KPOINTS_INPUT",
                    "No KPOINTS text given.", null);
        }
        if (text.length() > 512 * 1024) {
            return OperationResult.failed("VASP_KPOINTS_INPUT",
                    "KPOINTS text exceeds the 512 KiB audit bound ("
                            + text.length() + " chars) - bounded reads.",
                    null);
        }
        if (text.trim().isEmpty()) {
            return OperationResult.failed("VASP_KPOINTS_EMPTY",
                    "The KPOINTS text is empty.", null);
        }
        List<String> rawLines = new ArrayList<>();
        for (String line : text.split("\n", -1)) {
            String stripped = line.strip();
            if (!stripped.isEmpty()) {
                rawLines.add(stripped);
            }
        }
        // blank lines are tolerated in line mode (wiki); everywhere else the
        // grammar is positional, so skipping blanks matches VASP's reader.
        if (rawLines.size() < 3) {
            return OperationResult.failed("VASP_KPOINTS_SHAPE",
                    "A KPOINTS file needs at least 3 non-empty lines (comment,"
                            + " count, mode character); found " + rawLines.size(),
                    null);
        }
        List<String> notes = new ArrayList<>();
        String comment = rawLines.get(0);
        int count;
        try {
            count = Integer.parseInt(rawLines.get(1).split("\\s+")[0]);
        } catch (NumberFormatException problem) {
            return OperationResult.failed("VASP_KPOINTS_SHAPE",
                    "line 2 must be the k-point count (integer); got '"
                            + rawLines.get(1) + "'",
                    null);
        }
        if (count < 0) {
            return OperationResult.failed("VASP_KPOINTS_SHAPE",
                    "line 2 = " + count + ": negative k-point counts are not"
                            + " part of the pinned wiki grammar (0 = automatic"
                            + " mesh, >0 = explicit list / points per segment "
                            + "in line mode)",
                    null);
        }
        char selector = Character.toLowerCase(rawLines.get(2).charAt(0));
        if (selector == 'l') {
            return parseLineMode(comment, count, rawLines, notes);
        }
        if (count == 0) {
            return parseAutomatic(comment, selector, rawLines, notes);
        }
        return parseExplicit(comment, count, selector, rawLines, notes);
    }

    /** Auto mesh: G/M regular or generalized (C/c/K/k/R/r, or unknown char). */
    private static OperationResult<VaspKpointsDeck> parseAutomatic(String comment,
            char selector, List<String> lines, List<String> notes) {
        switch (selector) {
            case 'g', 'm' -> {
                if (lines.size() < 4) {
                    return OperationResult.failed("VASP_KPOINTS_SHAPE",
                            "automatic " + selector + "-mesh needs the"
                                    + " subdivisions line (N1 N2 N3) as line 4",
                    null);
                }
                String[] parts = lines.get(3).split("\\s+");
                int[] subdivisions = new int[3];
                try {
                    for (int i = 0; i < 3; i++) {
                        subdivisions[i] = Integer.parseInt(parts[i]);
                    }
                } catch (NumberFormatException | ArrayIndexOutOfBoundsException
                        problem) {
                    return OperationResult.failed("VASP_KPOINTS_SHAPE",
                            "line 4 of an automatic mesh must be three integers"
                                    + " (N1 N2 N3); got '" + lines.get(3) + "'",
                    null);
                }
                for (int n : subdivisions) {
                    if (n < 1) {
                        return OperationResult.failed("VASP_KPOINTS_SHAPE",
                                "subdivisions must be >= 1 (got " + n
                                        + "); VASP's automatic mode cannot"
                                        + " generate a mesh with zero divisions",
                    null);
                    }
                }
                double[] shift = new double[0];
                if (lines.size() >= 5) {
                    String[] sh = lines.get(4).split("\\s+");
                    try {
                        shift = new double[]{Double.parseDouble(sh[0]),
                                Double.parseDouble(sh[1]), Double.parseDouble(sh[2])};
                    } catch (NumberFormatException | ArrayIndexOutOfBoundsException
                            problem) {
                        return OperationResult.failed("VASP_KPOINTS_SHAPE",
                                "the optional shift line must hold three reals;"
                                        + " got '" + lines.get(4) + "'",
                    null);
                    }
                }
                if (lines.size() > 5) {
                    notes.add("trailing content after the shift line: "
                            + (lines.size() - 5) + " line(s) - not part of the"
                            + " pinned automatic-mesh grammar");
                }
                if (selector == 'm') {
                    notes.add("Monkhorst-Pack mesh: for EVEN subdivisions it is"
                            + " shifted by 1/2 versus the Gamma-centered one"
                            + " (wiki formulas); for fcc, hexagonal and"
                            + " fcc-orthorhombic lattices the wiki says use"
                            + " ONLY Gamma-centered meshes");
                }
                return OperationResult.success("VASP_KPOINTS_OK",
                        (selector == 'g' ? "Gamma-centered" : "Monkhorst-Pack")
                                + " automatic mesh",
                        new VaspKpointsDeck(comment,
                                selector == 'g' ? Mode.AUTO_GAMMA : Mode.AUTO_MP,
                                false, subdivisions, shift, new double[0][0],
                                0, List.of(), List.of(), List.of(), notes));
            }
            case 'c', 'k', 'r' -> {
                // generalized regular mesh: 3 generating vectors + shift
                notes.addAll(generalizedNotes());
                if (lines.size() < 7) {
                    return OperationResult.failed("VASP_KPOINTS_SHAPE",
                            "a generalized regular mesh needs 3 generating-"
                                    + "vector lines and a shift line after the"
                                    + " coordinate line; found " + lines.size()
                                    + " non-empty line(s)",
                    null);
                }
                double[][] generators = new double[3][3];
                for (int g = 0; g < 3; g++) {
                    String[] parts = lines.get(3 + g).split("\\s+");
                    try {
                        for (int i = 0; i < 3; i++) {
                            generators[g][i] = Double.parseDouble(parts[i]);
                        }
                    } catch (NumberFormatException | ArrayIndexOutOfBoundsException
                            problem) {
                        return OperationResult.failed("VASP_KPOINTS_SHAPE",
                                "generating-vector line " + (g + 1) + " must be"
                                        + " three reals; got '" + lines.get(3 + g)
                                        + "'",
                    null);
                    }
                }
                String[] sh = lines.get(6).split("\\s+");
                double[] shift;
                try {
                    shift = new double[]{Double.parseDouble(sh[0]),
                            Double.parseDouble(sh[1]), Double.parseDouble(sh[2])};
                } catch (NumberFormatException | ArrayIndexOutOfBoundsException
                        problem) {
                    return OperationResult.failed("VASP_KPOINTS_SHAPE",
                            "the generalized-mesh shift line must hold three"
                                    + " reals; got '" + lines.get(6) + "'",
                    null);
                }
                return OperationResult.success("VASP_KPOINTS_OK",
                        "generalized regular mesh",
                        new VaspKpointsDeck(comment, Mode.AUTO_GENERALIZED,
                                selector != 'r', new int[0], shift, generators,
                                0, List.of(), List.of(), List.of(), notes));
            }
            default -> {
                notes.add("third-line character '" + selector + "' is not G, M,"
                        + " C/c/K/k or R/r: VASP cannot interpret it, and the"
                        + " wiki states the RECIPROCAL generalized mesh is the"
                        + " default in that case - quoted advice: 'we recommend"
                        + " not relying on this behavior. Otherwise, the"
                        + " introduction of further automatic modes in the"
                        + " future versions of VASP may change the"
                        + " interpretation of the KPOINTS file.'");
                return parseAutomatic(comment, 'r', lines, notes);
            }
        }
    }

    /** The verbatim generalized-mesh commensurability note. */
    private static List<String> generalizedNotes() {
        List<String> out = new ArrayList<>();
        out.add("generalized regular mesh: 'The generating vectors g1, g2, and"
                + " g3 must be commensurate with the reciprocal lattice. This"
                + " means b_i = sum_j M_ij g_j where the matrix M contains only"
                + " integer entries' (wiki verbatim; VASP exits in error"
                + " otherwise)");
        return out;
    }

    /** Line mode (band paths), pinned wording of both wiki warnings. */
    private static OperationResult<VaspKpointsDeck> parseLineMode(String comment,
            int perSegment, List<String> lines, List<String> notes) {
        if (perSegment < 2) {
            return OperationResult.failed("VASP_KPOINTS_SHAPE",
                    "line mode needs at least 2 points per segment (second"
                            + " line = " + perSegment + ")",
                    null);
        }
        if (lines.size() < 4) {
            return OperationResult.failed("VASP_KPOINTS_SHAPE",
                    "line mode needs the coordinate-system line (line 4)",
                    null);
        }
        char coord = Character.toLowerCase(lines.get(3).charAt(0));
        boolean cartesian = coord == 'c' || coord == 'k';
        List<Vertex> vertices = new ArrayList<>();
        for (int li = 4; li < lines.size(); li++) {
            String[] parts = lines.get(li).split("\\s+");
            if (parts.length < 3) {
                return OperationResult.failed("VASP_KPOINTS_SHAPE",
                        "line-mode vertex line " + (li + 1) + " needs 3"
                                + " coordinates (optional label after); got '"
                                + lines.get(li) + "'",
                    null);
            }
            try {
                vertices.add(new Vertex(Double.parseDouble(parts[0]),
                        Double.parseDouble(parts[1]),
                        Double.parseDouble(parts[2]),
                        parts.length > 3 ? parts[3] : ""));
            } catch (NumberFormatException problem) {
                return OperationResult.failed("VASP_KPOINTS_SHAPE",
                        "line-mode vertex line " + (li + 1) + " has a"
                                + " non-numeric coordinate: '" + lines.get(li)
                                + "'",
                    null);
            }
        }
        if (vertices.size() < 2 || vertices.size() % 2 != 0) {
            return OperationResult.failed("VASP_KPOINTS_SHAPE",
                    "line mode needs PAIRS of vertex lines (each pair defines"
                            + " one path segment, wiki verbatim); found "
                            + vertices.size() + " vertex line(s)",
                    null);
        }
        notes.add("'The mesh generated by this mode is not suitable for"
                + " self-consistent calculations. Please set ICHARG = 11 to"
                + " avoid updating the density.' (wiki verbatim warning)");
        notes.add("'For meta-GGA and hybrid functionals, a regular mesh must"
                + " always be provided.' (wiki verbatim note)");
        notes.add("endpoints are included in every segment (" + perSegment
                + " points per segment here, so shared endpoints appear"
                + " twice - the wiki's own 'two X and W points' remark)");
        return OperationResult.success("VASP_KPOINTS_OK",
                "line mode, " + vertices.size() / 2 + " segment(s)",
                new VaspKpointsDeck(comment, Mode.LINE_MODE, cartesian,
                        new int[0], new double[0], new double[0][0],
                        perSegment, List.copyOf(vertices), List.of(),
                        List.of(), notes));
    }

    /** Explicit list (+ optional tetrahedra block), pinned notes. */
    private static OperationResult<VaspKpointsDeck> parseExplicit(String comment,
            int count, char selector, List<String> lines, List<String> notes) {
        boolean cartesian = selector == 'c' || selector == 'k';
        List<ExplicitPoint> points = new ArrayList<>();
        int li = 3;
        for (; li < lines.size() && points.size() < count; li++) {
            String[] parts = lines.get(li).split("\\s+");
            if (Character.toLowerCase(parts[0].charAt(0)) == 't') {
                // the wiki: the line after the points "must start with
                // 'T' or 't'" - first CHARACTER, so 'Tetrahedra' matches
                break;
            }
            if (parts.length < 4) {
                return OperationResult.failed("VASP_KPOINTS_SHAPE",
                        "explicit k-point line " + (li + 1) + " needs"
                                + " x y z weight; got '" + lines.get(li) + "'",
                    null);
            }
            try {
                points.add(new ExplicitPoint(Double.parseDouble(parts[0]),
                        Double.parseDouble(parts[1]),
                        Double.parseDouble(parts[2]),
                        Double.parseDouble(parts[3])));
            } catch (NumberFormatException problem) {
                return OperationResult.failed("VASP_KPOINTS_SHAPE",
                        "explicit k-point line " + (li + 1) + " has a"
                                + " non-numeric value: '" + lines.get(li) + "'",
                    null);
            }
        }
        if (points.size() != count) {
            return OperationResult.failed("VASP_KPOINTS_SHAPE",
                    "line 2 declares " + count + " explicit k-points but only "
                            + points.size() + " coordinate lines were found -"
                            + " VASP uses EXACTLY the provided points, so a"
                            + " short list is a shape error, never padded",
                    null);
        }
        notes.add("'VASP takes care that weights are properly normalized so"
                + " only relative weight is important' (wiki verbatim)");
        List<Tetra> tetras = new ArrayList<>();
        if (li < lines.size()
                && Character.toLowerCase(lines.get(li).charAt(0)) == 't') {
            if (li + 1 >= lines.size()) {
                return OperationResult.failed("VASP_KPOINTS_SHAPE",
                        "tetrahedra marker without the 'ntet volumeWeight'"
                                + " line",
                    null);
            }
            String[] head = lines.get(li + 1).split("\\s+");
            int ntet;
            try {
                ntet = Integer.parseInt(head[0]);
                Double.parseDouble(head[1]); // volume weight kept only in text
            } catch (NumberFormatException | ArrayIndexOutOfBoundsException
                    problem) {
                return OperationResult.failed("VASP_KPOINTS_SHAPE",
                        "the tetrahedra header must be 'ntet volumeWeight';"
                                + " got '" + lines.get(li + 1) + "'",
                    null);
            }
            for (int t = 0; t < ntet; t++) {
                int row = li + 2 + t;
                if (row >= lines.size()) {
                    return OperationResult.failed("VASP_KPOINTS_SHAPE",
                            "tetrahedra block declares " + ntet + " rows but"
                                    + " ends early",
                    null);
                }
                String[] parts = lines.get(row).split("\\s+");
                try {
                    tetras.add(new Tetra(Integer.parseInt(parts[0]),
                            Integer.parseInt(parts[1]),
                            Integer.parseInt(parts[2]),
                            Integer.parseInt(parts[3]),
                            Integer.parseInt(parts[4])));
                } catch (NumberFormatException | ArrayIndexOutOfBoundsException
                        problem) {
                    return OperationResult.failed("VASP_KPOINTS_SHAPE",
                            "tetrahedron row " + (t + 1) + " needs 5 integers"
                                    + " (degeneracy + 4 corner indices); got '"
                                    + lines.get(row) + "'",
                    null);
                }
            }
            for (Tetra tetra : tetras) {
                for (int corner : new int[]{tetra.c1(), tetra.c2(), tetra.c3(),
                        tetra.c4()}) {
                    if (corner < 1 || corner > count) {
                        return OperationResult.failed("VASP_KPOINTS_SHAPE",
                                "tetrahedron corner index " + corner + " is"
                                        + " outside 1.." + count
                                        + " (the wiki counts the explicit list"
                                        + " 1-based)",
                    null);
                    }
                }
            }
            notes.add("'VASP does not renormalize the weights of the"
                    + " tetrahedra. Make sure they are appropriately"
                    + " normalized.' (wiki verbatim warning)");
            li += 2 + ntet;
        }
        if (li < lines.size()) {
            notes.add("trailing content after the explicit list"
                    + (tetras.isEmpty() ? "" : " / tetrahedra block") + ": "
                    + (lines.size() - li) + " line(s) - not part of the pinned"
                    + " grammar");
        }
        return OperationResult.success("VASP_KPOINTS_OK",
                "explicit list, " + count + " k-point(s)"
                        + (tetras.isEmpty() ? "" : " + " + tetras.size()
                                + " tetrahedra"),
                new VaspKpointsDeck(comment, Mode.EXPLICIT, cartesian,
                        new int[0], new double[0], new double[0][0], 0,
                        List.of(), List.copyOf(points), List.copyOf(tetras),
                        notes));
    }

    // ================================ writer ================================

    /**
     * Canonical KPOINTS text of THIS deck (comment preserved; modes render
     * their pinned shapes). Explicit lists keep the parsed weight column
     * verbatim-as-doubles; the tetra block renders as 'T' + 'ntet
     * volumeWeight' + rows - the volume weight is recoverable only from the
     * ORIGINAL file (the parser keeps it in the note-free text), so when the
     * deck was built through factories it renders 1.0 with the multiplication
     * meaning stated by the wiki ('ratio between the volume of a tetrahedron
     * and the volume of the first Brillouin zone').
     */
    public String toKpointsText() {
        StringBuilder out = new StringBuilder();
        out.append(this.comment).append('\n');
        switch (this.mode) {
            case AUTO_GAMMA, AUTO_MP -> {
                out.append("0\n");
                out.append(this.mode == Mode.AUTO_GAMMA ? "Gamma\n"
                        : "Monkhorst-Pack\n");
                out.append(this.subdivisions[0]).append(' ')
                        .append(this.subdivisions[1]).append(' ')
                        .append(this.subdivisions[2]).append('\n');
                if (this.shift.length == 3) {
                    out.append(fmt(this.shift[0])).append(' ')
                            .append(fmt(this.shift[1])).append(' ')
                            .append(fmt(this.shift[2])).append('\n');
                }
            }
            case AUTO_GENERALIZED -> {
                out.append("0\n");
                out.append(this.cartesian ? "Cartesian\n" : "Reciprocal\n");
                for (double[] generator : this.generators) {
                    out.append(fmt(generator[0])).append(' ')
                            .append(fmt(generator[1])).append(' ')
                            .append(fmt(generator[2])).append('\n');
                }
                out.append(fmt(this.shift[0])).append(' ')
                        .append(fmt(this.shift[1])).append(' ')
                        .append(fmt(this.shift[2])).append('\n');
            }
            case LINE_MODE -> {
                out.append(this.pointsPerSegment).append('\n');
                out.append("line mode\n");
                out.append(this.cartesian ? "Cartesian\n" : "fractional\n");
                for (int v = 0; v < this.vertices.size(); v++) {
                    Vertex vertex = this.vertices.get(v);
                    out.append(fmt(vertex.x())).append(' ')
                            .append(fmt(vertex.y())).append(' ')
                            .append(fmt(vertex.z()));
                    if (!vertex.label().isEmpty()) {
                        out.append(' ').append(vertex.label());
                    }
                    out.append('\n');
                    if (v % 2 == 1 && v + 1 < this.vertices.size()) {
                        out.append('\n'); // segment separator, wiki template
                    }
                }
            }
            case EXPLICIT -> {
                out.append(this.points.size()).append('\n');
                out.append(this.cartesian ? "Cartesian\n" : "Reciprocal\n");
                for (ExplicitPoint point : this.points) {
                    out.append(fmt(point.x())).append(' ').append(fmt(point.y()))
                            .append(' ').append(fmt(point.z())).append("   ")
                            .append(fmt(point.weight())).append('\n');
                }
                if (!this.tetras.isEmpty()) {
                    out.append("Tetrahedra\n");
                    out.append(this.tetras.size()).append("  1.0\n");
                    for (Tetra tetra : this.tetras) {
                        out.append(tetra.degeneracy()).append(' ')
                                .append(tetra.c1()).append(' ')
                                .append(tetra.c2()).append(' ')
                                .append(tetra.c3()).append(' ')
                                .append(tetra.c4()).append('\n');
                    }
                }
            }
        }
        return out.toString();
    }

    /** Factory: Gamma-centered automatic mesh (+optional shift). */
    public static VaspKpointsDeck gammaMesh(String comment, int n1, int n2,
            int n3, double... shift) {
        return new VaspKpointsDeck(comment, Mode.AUTO_GAMMA, false,
                new int[]{n1, n2, n3},
                shift.length == 3 ? shift.clone() : new double[0],
                new double[0][0], 0, List.of(), List.of(), List.of(),
                List.of());
    }

    /** Factory: Monkhorst-Pack automatic mesh (+optional shift). */
    public static VaspKpointsDeck mpMesh(String comment, int n1, int n2,
            int n3, double... shift) {
        return new VaspKpointsDeck(comment, Mode.AUTO_MP, false,
                new int[]{n1, n2, n3},
                shift.length == 3 ? shift.clone() : new double[0],
                new double[0][0], 0, List.of(), List.of(), List.of(),
                List.of());
    }

    /** Factory: line-mode band path (vertex pairs, fractional default). */
    public static VaspKpointsDeck bandPath(String comment, int pointsPerSegment,
            boolean cartesian, List<Vertex> vertices) {
        return new VaspKpointsDeck(comment, Mode.LINE_MODE, cartesian,
                new int[0], new double[0], new double[0][0], pointsPerSegment,
                List.copyOf(vertices), List.of(), List.of(),
                List.of("'The mesh generated by this mode is not suitable for"
                        + " self-consistent calculations. Please set ICHARG = 11"
                        + " to avoid updating the density.' (wiki verbatim"
                        + " warning)"));
    }

    /** Factory: explicit list (weights kept relative, per the wiki note). */
    public static VaspKpointsDeck explicit(String comment, boolean cartesian,
            List<ExplicitPoint> points, List<Tetra> tetras) {
        return new VaspKpointsDeck(comment, Mode.EXPLICIT, cartesian,
                new int[0], new double[0], new double[0][0], 0, List.of(),
                List.copyOf(points), List.copyOf(tetras), List.of());
    }

    /** Locale-free token writer (integers stay integers, '.5' -> '0.5'). */
    public static String fmt(double value) {
        if (value == Math.floor(value) && Math.abs(value) < 1.0e15) {
            return Long.toString((long) value);
        }
        return Double.toString(value);
    }
}
