/*
 * Copyright (C) 2025-2026 QuantumForge Development Team.
 */
package quantumforge.run;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

import quantumforge.com.file.AtomicFileWriter;
import quantumforge.operation.OperationResult;
import quantumforge.ver.Version;

/**
 * Export a GUI-independent shell (and optional SLURM) script from a command DAG.
 */
public final class WorkflowExporter {

    public enum Format {
        BASH,
        SLURM
    }

    private WorkflowExporter() {
        // Utility.
    }

    public static OperationResult<Path> export(Path targetFile, QECommandDag dag, Format format,
                                               String jobName, int nodes, int ntasks, String partition) {
        Objects.requireNonNull(targetFile, "targetFile");
        Objects.requireNonNull(dag, "dag");
        Format fmt = format == null ? Format.BASH : format;
        try {
            String script = render(dag, fmt, jobName, nodes, ntasks, partition);
            AtomicFileWriter.writeUtf8(targetFile, script);
            return OperationResult.success("WORKFLOW_EXPORTED",
                    "Wrote " + fmt.name().toLowerCase(Locale.ROOT) + " workflow to " + targetFile,
                    targetFile);
        } catch (IOException ex) {
            return OperationResult.failed("WORKFLOW_EXPORT_FAILED",
                    "Could not write workflow script: " + ex.getMessage(), ex);
        }
    }

    static String render(QECommandDag dag, Format format, String jobName,
                         int nodes, int ntasks, String partition) {
        StringBuilder out = new StringBuilder();
        out.append("#!/usr/bin/env bash\n");
        out.append("set -euo pipefail\n");
        out.append("# Generated by ").append(Version.VERSION_NAME).append(' ')
                .append(Version.VERSION).append('\n');
        out.append("# Workflow: ").append(dag.getRunningType().name()).append('\n');
        out.append("# This script is independent of the QuantumForge GUI.\n\n");

        if (format == Format.SLURM) {
            String name = jobName == null || jobName.isBlank() ? "quantumforge-job" : jobName.trim();
            out.append("#SBATCH --job-name=").append(shellSingleQuote(name)).append('\n');
            out.append("#SBATCH --nodes=").append(Math.max(1, nodes)).append('\n');
            out.append("#SBATCH --ntasks=").append(Math.max(1, ntasks)).append('\n');
            if (partition != null && !partition.isBlank()) {
                out.append("#SBATCH --partition=").append(shellSingleQuote(partition.trim())).append('\n');
            }
            out.append("#SBATCH --output=%x-%j.out\n");
            out.append("#SBATCH --error=%x-%j.err\n\n");
        }

        out.append("echo \"QuantumForge exported workflow starting: $(date -u +%Y-%m-%dT%H:%M:%SZ)\"\n\n");
        List<QECommandStage> stages = dag.getStages();
        for (int i = 0; i < stages.size(); i++) {
            QECommandStage stage = stages.get(i);
            out.append("# Stage ").append(i).append(": ").append(stage.getLabel());
            if (stage.isOptional()) {
                out.append(" (optional)");
            }
            out.append('\n');
            out.append("echo \"==> ").append(stage.getId()).append("\"\n");
            String[] command = stage.getCommand();
            if (command.length == 0) {
                out.append("echo \"No command recorded for stage ").append(stage.getId())
                        .append("; configure QE paths before running.\" >&2\n");
                if (!stage.isOptional()) {
                    out.append("exit 2\n");
                }
            } else {
                out.append("set --");
                for (String token : command) {
                    out.append(' ').append(shellSingleQuote(token));
                }
                out.append('\n');
                if (stage.isOptional()) {
                    out.append("\"$@\" || echo \"Optional stage ").append(stage.getId())
                            .append(" failed; continuing.\" >&2\n");
                } else {
                    out.append("\"$@\"\n");
                }
            }
            out.append('\n');
        }
        out.append("echo \"QuantumForge exported workflow finished: $(date -u +%Y-%m-%dT%H:%M:%SZ)\"\n");
        return out.toString();
    }

    static String shellSingleQuote(String value) {
        if (value == null) {
            return "''";
        }
        return "'" + value.replace("'", "'\"'\"'") + "'";
    }
}
