/*
 * Copyright (C) 2025 QuantumForge Team
 */
package quantumforge.lammps;

/**
 * LAMMPS Molecular Dynamics integration.
 * 
 * NanoLabo supports LAMMPS for classical MD with:
 * - Multiple force fields (ReaxFF, AIREBO, EAM, etc.)
 * - GNN force field interface (M3GNet, CHGNet via LAMMPS)
 * - NVE, NVT, NPT ensembles
 * - Thermal conductivity (Green-Kubo)
 * - Viscosity coefficient
 * - Diffusion coefficient
 * - Radial distribution function
 * - Deformation (1D, 2D, 3D)
 * - Neural Network force fields
 * 
 * This integrates LAMMPS as a calculation engine alongside QE.
 */
public class LAMMPSInterface {

    public static final String FF_LJ = "lj/cut";
    public static final String FF_EAM = "eam";
    public static final String FF_AIREBO = "airebo";
    public static final String FF_REAX = "reax/c";
    public static final String FF_M3GNET = "m3gnet";
    public static final String FF_CHGNET = "chgnet";
    public static final String FF_DRUDE = "drude";
    public static final String FF_CLASS2 = "class2";

    public static final String ENSEMBLE_NVE = "nve";
    public static final String ENSEMBLE_NVT = "nvt";
    public static final String ENSEMBLE_NPT = "npt";
    public static final String ENSEMBLE_NPH = "nph";

    private String forceField;
    private String ensemble;
    private double temperature;
    private double pressure;
    private int timeSteps;
    private double timeStep;
    private boolean gpuEnabled;

    public LAMMPSInterface() {
        this.forceField = FF_LJ;
        this.ensemble = ENSEMBLE_NVT;
        this.temperature = 300.0;
        this.pressure = 0.0;
        this.timeSteps = 10000;
        this.timeStep = 1.0; // fs
        this.gpuEnabled = false;
    }

    // Getters and setters
    public void setForceField(String ff) { if (ff != null) this.forceField = ff; }
    public String getForceField() { return this.forceField; }

    public void setEnsemble(String ens) { if (ens != null) this.ensemble = ens; }
    public String getEnsemble() { return this.ensemble; }

    public void setTemperature(double T) { this.temperature = T; }
    public double getTemperature() { return this.temperature; }

    public void setPressure(double P) { this.pressure = P; }
    public double getPressure() { return this.pressure; }

    public void setTimeSteps(int steps) { this.timeSteps = Math.max(1, steps); }
    public int getTimeSteps() { return this.timeSteps; }

    public void setTimeStep(double dt) { this.timeStep = Math.max(0.1, dt); }
    public double getTimeStep() { return this.timeStep; }

    public void setGPUEnabled(boolean gpu) { this.gpuEnabled = gpu; }
    public boolean isGPUEnabled() { return this.gpuEnabled; }

    /**
     * Generate LAMMPS input script
     */
    public String generateInputScript() {
        StringBuilder sb = new StringBuilder();
        sb.append("# LAMMPS input generated by QuantumForge\n\n");
        sb.append("units           metal\n");
        sb.append("boundary        p p p\n");
        sb.append("atom_style      atomic\n\n");
        sb.append("read_data       structure.data\n\n");
        sb.append("pair_style      ").append(this.forceField).append("\n");
        sb.append("pair_coeff      * * ").append(getCoeffFile()).append("\n\n");
        sb.append("timestep        ").append(this.timeStep).append("\n\n");
        sb.append("velocity        all create ").append(this.temperature).append(" 12345\n\n");

        sb.append("fix             1 all ").append(this.ensemble);
        sb.append(" temp ").append(this.temperature);
        if (this.ensemble.equals(ENSEMBLE_NPT)) {
            sb.append(" iso ").append(this.pressure);
        }
        sb.append("\n\n");

        sb.append("thermo          100\n");
        sb.append("thermo_style    custom step temp press pe ke etotal\n\n");
        sb.append("dump            1 all xyz 1000 trajectory.xyz\n\n");
        sb.append("run             ").append(this.timeSteps).append("\n");

        return sb.toString();
    }

    private String getCoeffFile() {
        switch (this.forceField) {
            case FF_EAM: return "Fe_eam.fs";
            case FF_AIREBO: return "CH.airebo";
            case FF_REAX: return "ffield.reax";
            default: return "params.lj";
        }
    }
}
