/*
 * Copyright (C) 2025-2026 QuantumForge Team
 */

package quantumforge.builder;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

/**
 * Validates reaction networks, calculates temperature-dependent Gibbs free energy
 * corrections (harmonic ZPE, enthalpy, entropy), and exports standardized CatMAP
 * microkinetic modeling (.mkm) scripts (Roadmap #120).
 */
public final class QECatMapMkmExporter {

    public static final class ReactionStep {
        private final String expression; // e.g., "CO* + O* <-> CO2* + *"
        private final double barrierEv;  // Activation barrier

        public ReactionStep(String expression, double barrierEv) {
            this.expression = Objects.requireNonNull(expression, "expression").trim();
            this.barrierEv = Math.max(0.0, barrierEv);
        }

        public String getExpression() { return this.expression; }
        public double getBarrierEv() { return this.barrierEv; }
    }

    public static final class IntermediateSpecies {
        private final String label;           // e.g., "CO"
        private final double dftEnergyEv;     // DFT electronic energy of adsorption
        private final double[] frequenciesCm1; // Vibrational frequencies of the adsorbate

        public IntermediateSpecies(String label, double dftEnergy, double[] frequencies) {
            this.label = Objects.requireNonNull(label, "label").trim();
            this.dftEnergyEv = dftEnergy;
            this.frequenciesCm1 = frequencies != null ? frequencies.clone() : new double[0];
        }

        public String getLabel() { return this.label; }
        public double getDftEnergyEv() { return this.dftEnergyEv; }
        public double[] getFrequenciesCm1() { return this.frequenciesCm1.clone(); }
    }

    private final List<ReactionStep> steps = new ArrayList<>();
    private final List<IntermediateSpecies> speciesList = new ArrayList<>();

    public QECatMapMkmExporter() {
        // Constructor
    }

    public void addReactionStep(String expression, double barrier) {
        this.steps.add(new ReactionStep(expression, barrier));
    }

    public void addIntermediate(String label, double dftEnergy, double[] frequencies) {
        this.speciesList.add(new IntermediateSpecies(label, dftEnergy, frequencies));
    }

    public List<ReactionStep> getSteps() { return List.copyOf(this.steps); }
    public List<IntermediateSpecies> getSpeciesList() { return List.copyOf(this.speciesList); }

    /**
     * Calculates the temperature-dependent free energy correction for an intermediate
     * using the harmonic oscillator partition function:
     * G(T) = E_DFT + ZPE + H_vib(T) - T * S_vib(T)
     */
    public double calculateFreeEnergyEv(IntermediateSpecies sp, double tempK) {
        double energy = sp.getDftEnergyEv();
        if (sp.frequenciesCm1.length == 0) {
            return energy;
        }

        // Conversion factors
        double CM1_TO_EV = 1.23984e-4; // 1 cm-1 = 1.23984e-4 eV
        double KB_EV = 8.617333262145e-5; // eV/K

        double zpe = 0.0;
        double hVib = 0.0;
        double sVib = 0.0;

        for (double nu : sp.frequenciesCm1) {
            if (nu <= 0.0) {
                continue; // Skip imaginary modes
            }

            double hv = nu * CM1_TO_EV;
            zpe += 0.5 * hv;

            if (tempK > 0.0) {
                double x = hv / (KB_EV * tempK);
                if (x < 100.0) { // prevent overflow
                    double expX = Math.exp(x);
                    hVib += hv / (expX - 1.0);
                    sVib += KB_EV * (x / (expX - 1.0) - Math.log(1.0 - 1.0 / expX));
                }
            }
        }

        return energy + zpe + hVib - tempK * sVib;
    }

    /**
     * Generates a fully compliant, standard CatMAP microkinetic modeling (.mkm) input file.
     */
    public String generateMkmScript(double tempK, double pressureBar) {
        StringBuilder sb = new StringBuilder();
        sb.append("# CatMAP microkinetic model script generated by QuantumForge\n\n");
        
        sb.append("rxn_expressions = [\n");
        for (ReactionStep step : this.steps) {
            sb.append("    '").append(step.getExpression()).append("',\n");
        }
        sb.append("]\n\n");

        sb.append("temperature = ").append(String.format(Locale.ROOT, "%.2f", tempK)).append(" # Kelvin\n");
        sb.append("pressure = ").append(String.format(Locale.ROOT, "%.2f", pressureBar)).append(" # bar\n\n");

        sb.append("species_definitions = {}\n");
        for (IntermediateSpecies sp : this.speciesList) {
            double g = calculateFreeEnergyEv(sp, tempK);
            sb.append(String.format(Locale.ROOT, "species_definitions['%s*'] = {\n", sp.getLabel()));
            sb.append(String.format(Locale.ROOT, "    'free_energy': %.4f,\n", g));
            sb.append(String.format(Locale.ROOT, "    'dft_energy': %.4f,\n", sp.getDftEnergyEv()));
            sb.append("    'frequencies': ").append(formatArray(sp.frequenciesCm1)).append(",\n");
            sb.append("}\n");
        }

        return sb.toString();
    }

    private static String formatArray(double[] arr) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < arr.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(String.format(Locale.ROOT, "%.2f", arr[i]));
        }
        sb.append("]");
        return sb.toString();
    }

    /**
     * Writes the CatMAP .mkm script securely.
     */
    public void writeMkmFile(File file, double tempK, double pressureBar) throws IOException {
        if (file == null) {
            throw new IllegalArgumentException("file is null");
        }

        String content = generateMkmScript(tempK, pressureBar);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write(content);
        }
    }
}
